# -*- coding: utf-8 -*-
"""bike-sharing-solution-hour.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDmH8wnLUJ_ME-iGB14WYL6rZIuQo-lw

# Kaggle's "Bike sharing demand" challenge

## Introduction

In this test task you will have an opportunity to demonstrate your skills of a Data Scientist from various angles - processing data, analyzing and visualizing it, finding insights, applying predictive techniques and explaining your reasoning about it.

The task is based around a bike sharing dataset openly available at UCI Machine Learning Repository [1].

Please go through the steps below, build up the necessary code and comment on your choices.

## Part 1 - Data Loading and Environment Preparation

**Tasks:**
1. Prepare a Python 3 virtual environment (with virtualenv command). `requirements.txt` output of `pip freeze` command should be included as part of your submission.
2. Load the data from UCI Repository and put it into the same folder with the notebook. The link to it is https://archive.ics.uci.edu/ml/datasets/bike+sharing+dataset . Here is an available mirror in case the above website is down: https://data.world/uci/bike-sharing-dataset
3. We split the data into two parts. One dataset containing the last 30 days and one dataset with the rest.
"""

##########################################
# 1.2)  Load the data from UCI Repository and put it into the same folder with the notebook.
"""
# Create `data` directory, if it doesn't exist
!mkdir -p data

# Download the zipped archive from UCI
!wget -q --show-progress -P data http://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip

# Unzip to get `hour.csv`, `day.csv`, `Readme.txt`
!unzip -q data/Bike-Sharing-Dataset.zip -d data
"""
##########################################
# IMPORTS
##########################################
import pandas as pd
import numpy as np
from collections import deque
import matplotlib
matplotlib.use('Agg')   # non-GUI backend, safe for headless scripts
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import (
    RandomForestRegressor,
    HistGradientBoostingRegressor,
    GradientBoostingRegressor,
    )
from sklearn.base import clone
from sklearn.model_selection import cross_val_score
from sklearn.compose import ColumnTransformer, TransformedTargetRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.linear_model import LinearRegression
from pathlib import Path
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor
FIGDIR = Path.cwd() / "plots_day" # save all figures under ./plots
FIGDIR.mkdir(parents=True, exist_ok=True) # create the folder if missing


from utils import savefig_pdf
from eda_utils import iqr_mask
from ml_utils import _rmsle, rmsle_scorer, make_timeseries_split, Last30DaysSplit, BikeFeatureEngineer

"""## Part 2 - Data Processing and Analysis

**Tasks:**
1. Perform all needed steps to load and clean the data. Please comment the major steps of your code.
2. Visualise rentals of bikes per day.
3. Assume that each bike has exactly maximum 12 rentals per day.
    * Find the maximum number of bicycles `nmax` that was needed in any one day.
    * Find the 95%-percentile of bicycles `n95` that was needed in any one day.
5. Visualize the distribution of the covered days depending on the number of available bicycles (e.g. `nmax` bicycles would cover 100% of days, `n95` covers 95%, etc.)

"""

##########################################
# 2.1)  Perform all needed steps to load and clean data. Please comment the major steps of your code.
##########################################
# 2.1.1) Read raw data
hour_df = pd.read_csv('data/hour.csv')
print(f"Hourly dataset: {hour_df.shape[0]} rows x {hour_df.shape[1]} cols")
print(f"Its columns are {hour_df.columns.values}")
print(f"Raw data:\n{hour_df.head(2)}\n")

"""### Remarks about the cell below
Instead of dropping `casual` and `registered`, one could, alternatively:
1. train two separate models, one to predict `registered` and the other one to predict `casual`;
2. then, sum the two predictions to yield `cnt`

Pros: potentially better adaptability.
Cons:
- double training time. This might be negligible for decision trees, but this depend on their size (e.g. number of estimators) or training criteria (e.g.impurity criterion)
- prediction errors might add up more than by just predicting the single target `cnt`
"""

##########################################
# 2.1.2) No missing values by assumption
##########################################
# 2.1.3) Create new col with unique DateTime index `timestamp`, combines date + hour

# Sanity-check key columns before building timestamp (check for missing values)
na = hour_df.isna().sum()
if na.any():
    raise ValueError(f"Missing values in key columns for index: {na[na > 0].to_dict()}")

hour_df['timestamp'] = pd.to_datetime(hour_df['dteday']) + pd.to_timedelta(hour_df['hr'], unit='h')
hour_df = hour_df.set_index('timestamp').sort_index() # set as DataFrame index
# Drop 'instant' (just an ID), 'dteday' (now redundant), 'casual' and 'registered' (risk of target leakage)
hour_df = hour_df.drop(columns=['instant', 'dteday', 'casual', 'registered'])
print(f'Columns after dropping uninformative and leaky ones: {hour_df.columns}')
print()
# Statistics
print(hour_df.describe())
print()


"""### Remarks about the cell below
- the `iqr_mask()` function could be computed with Pandas' `quantile([0.25, 0.75])` as well
- the only column with a seemingly weird value seems to be `hum`, with a row being `0.0`: Washington is rearely so dry. Outlier flag!
"""

##########################################
# 2.1.4) Outlier detection (hourly)
iqr_mask(hour_df['hum'], 25, 75, 1.5)
# Replace impossible humidity zeros using previous/next hour.
outlier_humidity_mask = hour_df['hum'] == 0  # mask to flag implausible 0.0 humidity
hour_df.loc[outlier_humidity_mask, 'hum'] = np.nan  # set to NaN to mark as missing
# - `ffill()`: carry forward the last valid value in time (previous hour)
# - `bfill()`: use the next valid value in time (next hour) if needed
hour_df['hum'] = hour_df['hum'].ffill().bfill() # fill from previous hour, else from next hour
print()


##########################################
# 2.2)  Visualize rentals of bikes per day
##########################################
# 2.2.1) plot mean, rentals and rolling rentals (aggregate hourly -> daily)
daily_cnt = hour_df['cnt'].resample('D').sum() # aggregate hourly counts into daily totals
mean_cnt = daily_cnt.mean() # average daily rentals over the full period
window = 30 # rolling window length in days
# Smoothing: centered 30d rolling mean (`center=True` centers rolling window instead of right-aligned)
rolling_mean = daily_cnt.rolling(window=window, center=True).mean()
plt.figure(figsize=(12, 6)) # set plot size
# `alpha` sets some transparency for the daily count curve
plt.plot(daily_cnt.index, daily_cnt, label='Daily count', alpha=0.5) # Daily totals
plt.plot(daily_cnt.index, rolling_mean, label=f'{window}-day rolling mean', linewidth=2) # 30d rolling mean
plt.axhline(mean_cnt, color='red', linestyle='--', linewidth=2, label=f'Mean = {mean_cnt:.0f}') # overall mean
plt.title('Daily bike rentals') # title
plt.xlabel('Date') # x-axis label
plt.ylabel('Count') # y-axis label
plt.legend() # show legend
plt.tight_layout() # avoid label overlap
savefig_pdf("fig_daily_rentals", FIGDIR) # save to plots/fig_daily_rentals.pdf











"""### Remarks about the two cells below
- The distribution is almost normal-like. However...
- ...multimodality detected (3 peaks/clusters): potentially corresponding to 3 seasons? (maybe winter, summer, shoulder season);
- Presence of some extreme lows/highs, which might be outliers, or not: they could correspond to extremely pleasant days, or very snowy days. Below I applied the Tukey's IQR rule to exclude potential outliers. I found basically no outliers. The extreme points probably correspond to exceptionally bad or good weather days
- log-transform is left-skewed (log compresses high values and sparsifies small ones)
"""

##########################################
# 2.2.2) Plot marginal distribution (histogram bars and related KDE) of `cnt`
sns.histplot(hour_df['cnt'], bins=30, kde=True, kde_kws={'bw_adjust':0.7})
plt.title('Distribution of Daily Bike Rentals')
plt.xlabel('Daily rentals (cnt)')
plt.ylabel('Frequency')
plt.tight_layout()
savefig_pdf("fig_hist_cnt", FIGDIR)
# sns.pairplot(hour_df)
##########################################
# 2.2.3) Plot marginal distribution (histogram bars and related KDE) of `cnt` *after* log-transform
transformed = np.log1p(hour_df['cnt'])
sns.histplot(transformed, bins=30, kde=True, kde_kws={'bw_adjust':0.7})
plt.title('Distribution of Daily Bike Rentals (post log-transf.)')
plt.xlabel('Daily rentals (cnt)')
plt.ylabel('Frequency')
plt.tight_layout()
savefig_pdf("fig_hist_log_cnt", FIGDIR)

##########################################
# 2.2.4) Outlier detection and elimination
# traditional outlier range
iqr_mask(hour_df['cnt'], 25, 75, 1.5)
# loosened outlier range
iqr_mask(hour_df['cnt'], 25, 75, 1.0)

"""### Remarks about the cell below
It doesn't look like `weekday` should have a large predictive power, as a feature. Later, I tried removing it and training RFs without it. Since it improves the error, although very marginally, I decided to keep it
"""

##########################################
# 2.2.5) Visualize total bike rental count per weekday
plot_day_df = hour_df.copy() # Add readable weekday column
plot_day_df['day_of_week'] = plot_day_df.index.day_name()
# Displayed names, ordered
dow_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
plt.figure(figsize=(10,5))
sns.barplot(
    data = plot_day_df,
    x = 'day_of_week',
    y = 'cnt',
    estimator = sum, # aggregate by sum of rentals
    order = dow_order, # keep calendar order
    hue='day_of_week',
    dodge=False, # avoid side-by-side bars
    # legend=False, # no legend needed since x-axis already labels
    palette = sns.color_palette("colorblind", 7)
)
plt.xlabel('Day of the week')
plt.ylabel('Total rentals (2011-2012)')
plt.title('Bike-sharing demand by weekday (sum over two years)')
plt.xticks(rotation=45)
plt.tight_layout()
savefig_pdf("fig_weekday_totals", FIGDIR)


##########################################
# 2.2.6) Visualize total bike rental count per  month
plot_day_df = hour_df.copy() # Add readable month column
plot_day_df['month_name'] = plot_day_df.index.month_name()
# Displayed names, ordered
month_order = ['January','February','March','April','May','June',
               'July','August','September','October','November','December']
plt.figure(figsize=(12,5))
sns.barplot(
    data=plot_day_df,
    x='month_name',
    y='cnt',
    estimator=sum, # aggregate by sum of rentals
    order=month_order,
    hue='month_name',
    dodge=False,
    legend=False,
    palette=sns.color_palette("colorblind", 12)
)

plt.xlabel('Month')
plt.ylabel('Total rentals (2011-2012)')
plt.title('Bike-sharing demand by month (sum over two years)')
plt.xticks(rotation=45)
plt.tight_layout()
savefig_pdf("fig_month_totals", FIGDIR)


##########################################
# 2.2.7) Visualize total bike rental count per season
plot_day_df = hour_df.copy()
season_map = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'} # Map numeric season codes to names
plot_day_df['season_name'] = plot_day_df['season'].map(season_map)
season_order = ['Spring', 'Summer', 'Fall', 'Winter'] # Displayed names, ordered
plt.figure(figsize=(8,5))
sns.barplot(
    data = plot_day_df,
    x = 'season_name',
    y = 'cnt',
    estimator = sum,
    order = season_order,
    hue='season_name',
    dodge=False,
    legend=False,
    palette = sns.color_palette("colorblind", 4)
)
plt.xlabel('Season')
plt.ylabel('Total rentals (2011-2012)')
plt.title('Bike-sharing demand by season (sum over two years)')
plt.tight_layout()
savefig_pdf("fig_season_totals", FIGDIR)


##########################################
# 2.2.8) Exploring multimodality in `cnt`: visualize distplot (KDE) and histplot (histograms)
# KDE for each season (smoothed estimated histogram distro): basically show PDF for each season
g = sns.displot(
    data=hour_df.assign(season=hour_df['season'].map(season_map)),
    x='cnt',
    hue='season',
    kind='kde',
    clip=(0, None),
    fill=False,
    common_norm=False,
    height=4,
    aspect=1.4
).set(title='Daily rental distribution by season')
g.savefig(FIGDIR / "fig_kde_by_season.pdf")  # FacetGrid has savefig
plt.close(g.fig)
# Histograms for each seasonal distribution
g = sns.FacetGrid(
        hour_df.assign(season=hour_df['season'].map(season_map)),
        col='season',
        col_wrap=2,
        height=3.2
    )
g.map(sns.histplot, 'cnt', bins=20, color='steelblue')
g.set_axis_labels('Daily rentals (cnt)', 'N. of days')
g.savefig(FIGDIR / "fig_hist_by_season.pdf")
plt.close(g.fig)

r"""### Remarks about the cell below
- `atemp` is so highly corr. with `temp` (0.99) that they are basically the same $\to$ drop
- `season` is highly corr. with `month` (0.83). However, since a) RFs don't suffer from highly correlated features that much, and b) I experimented with dropping `season` and this worsened the final test score $\to$ I decided to keep it
"""

##########################################
# 2.2.9) Visualize correlation matrix
print(hour_df.columns)
corr = hour_df[['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed']].corr()
mask = np.array(corr)
mask[np.tril_indices_from(mask)] = False
fig, ax= plt.subplots()
fig.set_size_inches(20,10)
sns.heatmap(corr, mask=mask, vmax=.8, square=True, annot=True)
plt.tight_layout()
savefig_pdf("fig_corr_pre", FIGDIR, fig)

##########################################
# 2.3)  Assume that each bike has exactly maximum 12 rentals per day
# - Find the maximum number of bicycles nmax that was needed in any one day.
# - Find the 95%-percentile of bicycles n95 that was needed in any one day.
##########################################
# Compute the fleet size needed per day, assuming each bike is rented <=12 times daily (convert to int)
hour_df['daily_fleet_size'] = np.ceil(hour_df['cnt'] / 12).astype(int)
# Compute stats:
#   - `nmax`: fleet size needed to cover demand on "busiest" day
#   - `n95`: 95-th percentile fleet size on (smallest fleet inventory that would have covered 95% of days)
nmax = hour_df['daily_fleet_size'].max()
n95  = int(np.ceil(np.percentile(hour_df['daily_fleet_size'], 95)))
n50  = int(np.ceil(np.percentile(hour_df['daily_fleet_size'], 50)))
print(f"Number of bikes needed on busiest day (nmax): {nmax}")
print(f"Smallest number of bikes to cover 95% of days (n95): {n95}")
print()

##########################################
# 2.4)  Visualize the distribution of the covered days depending on the number of available bicycles.
#       E.g. `nmax` bicycles would cover 100% of days, `n95` covers 95%, etc.
##########################################
# Build "coverage" curve. For every `daily_fleet_size` value k, compute proportion of days with demand <= k.
# Basically, compute empirical CDF (in %): P("bikes needed" <= k)) in [0,1]
coverage_df = (
    hour_df['daily_fleet_size']
    .value_counts() # for each `daily_fleet_size` value k, count n. of days which required exactly k bikes (Series, indexed by k)
    .sort_index() # sort by bike count k (ascending)
    .cumsum() # running cumulative sum, represents days where <= k bikes needed
    / len(hour_df) * 100 # convert into percentage ~CDF
    ).reset_index().rename(columns={'daily_fleet_size': 'k', 'count': 'emp_CDF'})
# Plot: needed fleet size `k` vs %of days covered `emp_CDF`
plt.figure(figsize=(10, 6))
# Empirical CDF is flat until a new value of k is attained, then jumps up:
#   - `plt.step`: draws that step-curve
#   - `where='post'`: means hold current CDF value until next x-tick (i.e., next CDF value is attained), then jump
plt.step(coverage_df['k'], coverage_df['emp_CDF'], where='post')
# Vertical dashed line at 50th, 95th and 100th (max) percentiles of fleet size
plt.axvline(n50, linestyle='--', label=f'n50 = {n50}', color='#0072B2')
plt.axvline(n95, linestyle='--', label=f'n95 = {n95}', color='#D55E00')
plt.axvline(nmax, linestyle='--', label=f'nmax = {nmax}', color='#009E73')
plt.xlabel('N. needed bicycles (k)')
plt.ylabel('% of fully served days (demand ≤ k)')
plt.title(f'Daily coverage for different bicycle fleet sizes k, over {len(hour_df)} days')
plt.grid(True, linestyle=':') # light dotted grid
plt.legend()
plt.tight_layout()
savefig_pdf("fig_coverage_ecdf", FIGDIR)

"""## Part 3 - Building prediction models

**Tasks:**
1. Define a test metric for predicting the daily demand for bike sharing, which you would like to use to measure the accuracy of the constructed models, and explain your choice.
2. Build a demand prediction model with Random Forest, preferably making use of following python libraries: scikit-learn.
3. Report the value of the chosen test metric on the provided data.
"""

##########################################
# Data
X = hour_df.copy(deep=True)
X = hour_df.copy(deep=True).drop(columns=['daily_fleet_size'])
y = X['cnt']
print(f'Columns before any feature engineering: {X.columns.values}')
print()

r"""### 3.0) Feature engineering: log (Box-Cox) transform + revert
-   **Compresses outliers**, reducing their relative importance $\to$ now big and small rental days (e.g. vv hot or vv cold days) are comparable on an "additive scale", and additive effects should be more easily"measured"/"estimated" by models than multiplicative effect. So, our trees will tolerate more error on these outliers while being more accurate on the bulk of data.
-   **Var is more uniform/stabilized**, while not changing the ranking of the values $\to$ improved split-point detection in decision trees. What happens is that, in RFs, each tree make splits by minimizing the variance of the children (impurity-based); in the end, since the label/prediction at the leaves is a mean, on the leaves RF basically minimize the sum of variances. Now, if the target is skewed, outliers will affect the variances and worsen splits: split points are pushed towards the outliers, as a tree tries to "isolate" the tail from the remaining points $\to$ trees will be more affected by outliers if data is not transformed, i.e., they will predict outliers more accurately

See empirical performance at end, showcasing a superior performance with log-transform

### 3.1) Define a test metric for predicting the daily demand for bike sharing, which you would like to use to measure the accuracy of the constructed models, and explain your choice.

Chosen: Root Mean Squared Log Error (RMSLE): $\sqrt{\dfrac{1}{n}\sum_{i \in [n]}\Bigl(\log(\hat{y}_i+1) - \log(y_i+1)\Bigr)^2}$
- each summand in the loss is roughly equivalent to $≈\log^2\left(\dfrac{\hat{y_i}}{y_i}\right)$, with $\hat{y_i}$ a prediction and $y_i$ a label
- **asymmetric costs**: RMSLE yields a larger penalty for under-predictions: basically grows exponentially for underpredictions and less than logarithmically for overprediction. This is more useful than, say, MAE and MSE, which are "cost-symmetric" (no difference between under and over predictions). In fact, while over-predicting might not a big issue (e.g., if we prepared more bikes at a spot for one day, we could always move some during the night...or have them at the ready for the day after, the assumption being that people are always willing to move a bit to get to a bike), but under-predicting is bad because we cannot satisfy demand and thus lose money
- **robustness to outliers**: the log makes it robust to outliers, with similar considerations as the ones made about the log-transform. Useful considering that the data in `cnt` has a wide range of values (almost 3 orders of magnitude, from 22 to 8714). Also useful because it can predict relative errors well, and we are more interested in them than absolute errors (for instance, predicting 9 instead of 10 has the same RMSLE as predicting 900 instead of 1000).

### Remarks about the cells below
#### About Pipelines
I used sklearn's Pipelines used, so in the cells below I define some helper functions or classes that I will call in `eval_pipeline`, which
1. perform a train/test split $\to$ see `Month20tr10teSplit` and `Last30DaysSplit`
2. do feature engineering and potentially applies target transformation $\to$ see `preprocess` (applying no feature engineering), `one_hot_no_sparse` (setting up a one-hot encoder), `BikeFeatureEngineer`. This last one contains:
  - drop highly correlated features
  - compute cyclical sin/cos transformation features, important because they enforce continuity (e.g. Monday is close to Sunday)
  - optionally, add autoregressive features using past data: 1-day lag and 7-day rolling median. Note that this does not leak info and is feasible for production
3. fit a predictor, then evaluates it on a test set $\to$ see `eval_pipeline`

#### About splits
I use two splits: one with last 30 days as test set, and another with a time series split to avoid data leakage. I avoid random splits to prevent leaking future info.
"""

##########################################
# 3.2) Build a demand prediction model with Random Forest, preferably making use of following python libraries: scikit-learn.






##########################################
# 3.2.2) NO Feature engineering
# all columns but `cnt`
feat_cols = [c for c in X.columns if c != 'cnt']
# "Preprocess-only" block used by to perform *no* feature engineering
preprocess = ColumnTransformer([('keep_all', 'passthrough', feat_cols)], remainder='drop')

# Convert array output back to DataFrame with original `feat_cols` names
# Only needed for `lightgbm` to preserve feature names and avoid warning
to_df = FunctionTransformer(
    lambda A: pd.DataFrame(A, columns=feat_cols),
    feature_names_out=lambda self, input_features=None: np.array(feat_cols)
)


##########################################
# 3.2.4) Pipeline evaluation
def eval_pipeline(pipe, X, y, cv):
    scores = cross_val_score(
        pipe, # Clone pipeline/estimator
        X, y, # Data
        cv = cv, # Splitting procedure
        scoring = rmsle_scorer # returns -RMSLE (lower is better)
        )
    return -scores.mean()

def eval_pipeline_walkforward(pipe, X, y, cv):
    """
    Evaluate pipeline with AR features in a recursive, walk-forward manner.

    - Builds test-day AR features using previous test-day predictions, not true labels. This: 
      a) mirrors deployment (true future `cnt` unknown
      b) prevents look-ahead leakage when computing features (using labels would yield overly optimistic scores)
    - Initializes test-time AR features using last training `cnt` values (`self._carry_`)

    Input:
    - `pipe`: sklearn `Pipeline` with a `fe` step (`BikeFeatureEngineer`) and a `model` step
    - `X`: DataFrame of features including `cnt` used only to construct AR features
    - `y`: Series of labels aligned with `X`
    - `cv`: splitter yielding train/test indices in time order

    Output:
    - `float`: mean RMSLE across folds
    """
    scores = []  # Store RMSLE scores for each fold
    for tr_idx, te_idx in cv.split(X):
        # Split data into train and test sets for current fold
        X_tr, y_tr = X.iloc[tr_idx], y.iloc[tr_idx]
        X_te, y_te = X.iloc[te_idx], y.iloc[te_idx]

        # Clone pipeline and fit on training data
        estimator = clone(pipe).fit(X_tr, y_tr)

        # Check that pipeline has `fe` step
        if 'fe' not in estimator.named_steps:
            raise ValueError("eval_pipeline_walkforward requires a 'fe' step (BikeFeatureEngineer).")
        fe = estimator.named_steps['fe']  # `fe` is feature engineering step (`BikeFeatureEngineer`)
        model = estimator.named_steps['model']  # `model` is final estimator (could be regressor or wrapper)

        preds = []  # Store predictions for test set
        # Walk forward through test set, one day at a time
        for k in range(len(X_te)):
            te_prefix = X_te.iloc[:k+1].copy()  # Indexed from 0 to k+1 of test set
            # Replace true test labels in `te_prefix['cnt']` with previous predictions ("proxy" labels)
            # Current day receives NaN, past days use predictions
            # Rationale: at deployment we wouldn't have true future labels `cnt`, so we must use predictions to form `lag1`/`roll7`.
            #   `BikeFeatureEngineer.transform` uses `te_prefix['cnt']` to build AR features and then DROPS it.
            cnt_proxy = pd.Series(preds + [np.nan], index=te_prefix.index, dtype='float64')
            te_prefix['cnt'] = cnt_proxy.values

            # Transform features for current day. AR features built using predictions instead of true labels (unavailable in real scenarios) 
            last_row_features = fe.transform(te_prefix).iloc[[-1]] # last row
            y_hat = model.predict(last_row_features).item()  # Predict for current day, extract scalar
            preds.append(float(y_hat))  # Store prediction as float

        # Compute RMSLE for this fold and append to scores
        scores.append(_rmsle(y_te, pd.Series(preds, index=y_te.index)))
    # Return mean RMSLE across all folds
    return float(np.mean(scores))

"""#### About baselines
I decided to use two "autoregressive" baselines.
Rationale: this is what we would do if we could not use ML. We would use past data, either 1-day lag or 7-day rolling median.

"""

##########################################
# 3.2.5) Simple autoregressive baseline
def ar_baseline_scores(y, splitter, window=7):
    """
    Return RMSLE for two autoregressive baselines on the test indices generated by `splitter`:
      - `lag-1`: predict yesterday's *prediction* (not true label) in test
      - `roll-7`: predict median of last `window` (predictions/observations available up to that day)
    Baselines use last available training values to initialize prediction history; baselines never use test labels

    Input:
    - `y`: Series of labels
    - `splitter`: cross-validation splitter yielding train/test indices
    - `window`: window size for rolling median

    Output:
    - `float`: mean RMSLE for lag-1 baseline
    - `float`: mean RMSLE for roll-7 baseline
    """
    lag_scores, roll_scores = [], []  # Store RMSLE scores for lag-1 and roll-7 baselines
    y = y.copy()  # Avoid modifying original `y`

    for tr_idx, te_idx in splitter.split(y.to_frame()):
        tr_idx = np.asarray(tr_idx)  # Convert `tr_idx` to numpy array
        te_idx = np.asarray(te_idx)  # Convert `te_idx` to numpy array
        y_tr = y.iloc[tr_idx]        # Get training labels for current split
        y_te = y.iloc[te_idx]        # Get test labels for current split

        # Initialize buffer for lag-1 with last value from `y_tr` (simulate only knowing past)
        # Use `deque` for efficient rolling window updates (append/pop from ends in O(1) time)
        buf_lag  = deque(y_tr.tail(1).tolist(), maxlen=window)
        # Initialize roll-7 buffer with last `window` values from `y_tr`
        buf_roll = deque(y_tr.tail(window).tolist(), maxlen=window)

        preds_lag, preds_roll = [], []  # Store predictions for each baseline

        # Walk forward through test indices, simulating prediction day by day
        for _ in te_idx:
            # Lag-1: prediction is last value in `buf_lag, i.e., previous day's prediction
            p_lag = float(buf_lag[-1])
            preds_lag.append(p_lag)
            buf_lag.append(p_lag)  # Update buffer with prediction (recursive, always use previous prediction)

            # Roll-7: prediction is median of values in `buf_roll` (uses only predictions/observations up to that day)
            p_roll = float(np.median(buf_roll))
            preds_roll.append(p_roll)
            buf_roll.append(p_roll)  # Update buffer with prediction (recursive)

        # Compute RMSLE for lag-1 baseline for this split
        lag_scores.append(_rmsle(y_te, pd.Series(preds_lag, index=y_te.index)))
        # Compute RMSLE for roll-7 baseline for this split
        roll_scores.append(_rmsle(y_te, pd.Series(preds_roll, index=y_te.index)))

    # Return mean RMSLE for both baselines across all splits
    return float(np.mean(lag_scores)), float(np.mean(roll_scores))

# Instantiate splitters
cv_last30 = Last30DaysSplit()
cv_ts_ar  = make_timeseries_split(add_lag1=True,  add_roll7=True,  n_splits=5, test_size=30)
cv_ts_no  = make_timeseries_split(add_lag1=False, add_roll7=False, n_splits=5, test_size=30)

# Evaluate autoregressive baselines
lag1_30, roll7_30 = ar_baseline_scores(y, cv_last30, window=7)
lag1_ts, roll7_ts = ar_baseline_scores(y, cv_ts_ar,  window=7)
print(f'Last-30 split baseline (lag-1), RMSLE : {lag1_30:.6f}')
print(f'Last-30 split baseline (roll-7), RMSLE : {roll7_30:.6f}')
print(f'Time-series split baseline (lag-1), RMSLE : {lag1_ts:.6f}')
print(f'Time-series split baseline (roll-7), RMSLE : {roll7_ts:.6f}')
print()

##########################################
# 3.2.6) Our Base regressor and splitters
def make_model(name: str):
    if name == "rf":
        return RandomForestRegressor(
            n_estimators = 50,
            min_samples_leaf = 2,
            criterion = 'friedman_mse',
            random_state = 42)
    if name == "hgbr":
        return HistGradientBoostingRegressor(
            learning_rate=0.05,
            max_iter=500,
            early_stopping=True,
            random_state=42)
    if name == "gbr":
        return GradientBoostingRegressor(
            learning_rate=0.05,
            n_estimators=500,
            max_depth=3,
            random_state=42)
    if name == "xgb":
        return XGBRegressor(
            n_estimators=500,
            learning_rate=0.05,
            max_depth=6,
            subsample=0.8,
            colsample_bytree=0.8,
            objective='reg:squarederror',
            tree_method='hist',
            random_state=42,
            n_jobs=-1,
        )
    if name == "cbr":
        return CatBoostRegressor(
            iterations=800,
            learning_rate=0.05,
            depth=6,
            loss_function='RMSE',
            random_seed=42,
            verbose=False,
        )
    if name == "lgbm":
        return LGBMRegressor(
            n_estimators=800,
            learning_rate=0.05,
            num_leaves=63,              # more leaf capacity
            min_child_samples=10,       # allow smaller leaves (alias of min_data_in_leaf)
            max_depth=-1,
            subsample=0.8,
            colsample_bytree=0.8,
            objective='rmse',
            force_col_wise=True,        # remove col/row test overhead message
            verbosity=-1,               # silence LightGBM logs
            random_state=42,
        )
    raise ValueError(f"Unknown model '{name}'")

hgbr = make_model("hgbr")
rf   = make_model("rf")
gbr  = make_model("gbr")
xgb  = make_model("xgb")
cbr  = make_model("cbr")
lgbm = make_model("lgbm")

r"""#### About test results (autoregressive baselines VS simple RF baseline)
- `cv_last30` split: autocorrelation is strong and, in a sense, bike rental demand is persistent to the 1-day lag. In fact:
  - the 1-day lag autoregressive baseline is good, actually better than our naive random forest with og-scaled target and no feature engineering. But already when we log-transform we are better than naive baseline, and then adding FE we improve even more.
  - note that our RF is better on this split when autoregressive feature are used WRT no AR features
- `cv_20_10` split: our RF is already better than the autoregressive baselines on this "more challenging split". Our calendar+weather RF improves once we stabilise variance (with log-target) and add basic feature engineering. Autoregressive features worsen the test scores. It would be interesting to perform experiments on a larger dataset
- the log-transform (transform `y_train`, then backtransform `y_pred` before computing the RMSLE) always yields better test results

#### Takeaways
- `cv_last30`: our best model (with feature engineering including autoregressive features, and target log-transform) reduces the 1-day lag baseline error by about $18\%$, and the 7-day rolling median baseline by about $33\%$.
- `cv_last30`: on this tougher split, our best model (with feature engineering not including autoregressive features, and target log-transform) reduces the 1-day lag baseline error by about $19\%$, and the 7-day rolling median baseline by about $14\%$.
- **log-transform**: always produces improvements in test error: at least $2\%$ and as much $16\%$ WRT un-transformed target
- **autoregressive features**: could be useful but to be verified with larger dataset
"""

##########################################
# 3.2.7) Evaluate our pipeline without feature engineering
##########################################
# Raw pipeline without log-transform
pipe_rf_raw = Pipeline([ # rf
    ('prep' , preprocess),
    ('model', rf)
])
pipe_hgbr_raw = Pipeline([ # hgbr
    ('prep' , preprocess),
    ('model', hgbr)
])
pipe_gbr_raw = Pipeline([ # gbr
    ('prep', preprocess),
    ('model', gbr)
])
pipe_xgb_raw = Pipeline([ # xgb
    ('prep', preprocess),
    ('model', xgb)
])
pipe_cbr_raw = Pipeline([ # catboost
    ('prep', preprocess),
    ('model', cbr)
])
pipe_lgbm_raw = Pipeline([ # lightgbm
    ('prep', preprocess),
    ('to_df', to_df),
    ('model', lgbm)
])
##########################################
# Pipeline with log-transform and back
pipe_rf_logtransf = Pipeline([ # rf
    ('prep' , preprocess),
    ('model', TransformedTargetRegressor(
        regressor = rf,
        func = np.log1p,   # log-transform `y_train`
        inverse_func = np.expm1)) # revert `y_pred` to og scale to compute RMSLE
])
pipe_hgbr_logtransf = Pipeline([ # hgbr
    ('prep' , preprocess),
    ('model', TransformedTargetRegressor(
        regressor = hgbr,
        func = np.log1p,
        inverse_func = np.expm1))
])
pipe_gbr_logtransf = Pipeline([ # gbr
    ('prep', preprocess),
    ('model', TransformedTargetRegressor(
        regressor=gbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_xgb_logtransf = Pipeline([ # xgb
    ('prep', preprocess),
    ('model', TransformedTargetRegressor(
        regressor=xgb, func=np.log1p, inverse_func=np.expm1))
])
pipe_lgbm_logtransf = Pipeline([ # lightgbm
    ('prep', preprocess), # your passthrough by names
    ('to_df', to_df), # keep names for downstream estimator
    ('model', TransformedTargetRegressor(
        regressor=lgbm, func=np.log1p, inverse_func=np.expm1))
])
rmsle_xgb_last30_raw = eval_pipeline(pipe_xgb_raw, X, y, cv_last30)
rmsle_xgb_last30_log = eval_pipeline(pipe_xgb_logtransf, X, y, cv_last30)
rmsle_xgb_ts_raw     = eval_pipeline(pipe_xgb_raw, X, y, cv_ts_no)
rmsle_xgb_ts_log     = eval_pipeline(pipe_xgb_logtransf, X, y, cv_ts_no)
pipe_cbr_logtransf = Pipeline([ # catboost
    ('prep', preprocess),
    ('model', TransformedTargetRegressor(
        regressor=cbr, func=np.log1p, inverse_func=np.expm1))
])
rmsle_cbr_last30_raw = eval_pipeline(pipe_cbr_raw, X, y, cv_last30)
rmsle_cbr_last30_log = eval_pipeline(pipe_cbr_logtransf, X, y, cv_last30)
rmsle_cbr_ts_raw     = eval_pipeline(pipe_cbr_raw, X, y, cv_ts_no)
rmsle_cbr_ts_log     = eval_pipeline(pipe_cbr_logtransf, X, y, cv_ts_no)
rmsle_rf_last30_raw = eval_pipeline(pipe_rf_raw, X, y, cv_last30)
rmsle_rf_last30_log = eval_pipeline(pipe_rf_logtransf, X, y, cv_last30)
rmsle_rf_ts_raw = eval_pipeline(pipe_rf_raw, X, y, cv_ts_no)
rmsle_rf_ts_log = eval_pipeline(pipe_rf_logtransf, X, y, cv_ts_no)
rmsle_hgbr_last30_raw = eval_pipeline(pipe_hgbr_raw, X, y, cv_last30)
rmsle_hgbr_last30_log = eval_pipeline(pipe_hgbr_logtransf, X, y, cv_last30)
rmsle_hgbr_ts_raw     = eval_pipeline(pipe_hgbr_raw, X, y, cv_ts_no)
rmsle_hgbr_ts_log     = eval_pipeline(pipe_hgbr_logtransf, X, y, cv_ts_no)
rmsle_gbr_last30_raw = eval_pipeline(pipe_gbr_raw, X, y, cv_last30)
rmsle_gbr_last30_log = eval_pipeline(pipe_gbr_logtransf, X, y, cv_last30)
rmsle_gbr_ts_raw     = eval_pipeline(pipe_gbr_raw, X, y, cv_ts_no)
rmsle_gbr_ts_log     = eval_pipeline(pipe_gbr_logtransf, X, y, cv_ts_no)
rmsle_xgb_last30_raw = eval_pipeline(pipe_xgb_raw, X, y, cv_last30)
rmsle_xgb_last30_log = eval_pipeline(pipe_xgb_logtransf, X, y, cv_last30)
rmsle_xgb_ts_raw     = eval_pipeline(pipe_xgb_raw, X, y, cv_ts_no)
rmsle_xgb_ts_log     = eval_pipeline(pipe_xgb_logtransf, X, y, cv_ts_no)
rmsle_lgbm_last30_raw = eval_pipeline(pipe_lgbm_raw, X, y, cv_last30)
rmsle_lgbm_last30_log = eval_pipeline(pipe_lgbm_logtransf, X, y, cv_last30)
rmsle_lgbm_ts_raw     = eval_pipeline(pipe_lgbm_raw, X, y, cv_ts_no)
rmsle_lgbm_ts_log     = eval_pipeline(pipe_lgbm_logtransf, X, y, cv_ts_no)
print(f"RF + no FE Last30 split, raw : {rmsle_rf_last30_raw:.6f}")
print(f"RF + no FE, Last30 split, log : {rmsle_rf_last30_log:.6f}")
print(f"HGBRT + no FE, Last30 split, raw : {rmsle_hgbr_last30_raw:.6f}")
print(f"HGBRT + no FE, Last30 log, log : {rmsle_hgbr_last30_log:.6f}")
print(f"GBRT + no FE, Last30 split, raw : {rmsle_gbr_last30_raw:.6f}")
print(f"GBRT + no FE, Last30 split, log : {rmsle_gbr_last30_log:.6f}")
print(f"XGB + no FE, Last30 split, raw : {rmsle_xgb_last30_raw:.6f}")
print(f"XGB + no FE, Last30 split, log : {rmsle_xgb_last30_log:.6f}")
print(f"CAT + no FE, Last30 split, raw : {rmsle_cbr_last30_raw:.6f}")
print(f"CAT + no FE, Last30 split, log : {rmsle_cbr_last30_log:.6f}")
print(f"LGBM + no FE, Last30 split, raw : {rmsle_lgbm_last30_raw:.6f}")
print(f"LGBM + no FE, Last30 split, log : {rmsle_lgbm_last30_log:.6f}")
print(f"RF + no FE, TS split, raw : {rmsle_rf_ts_raw:.6f}")
print(f"RF + no FE, TS split, log : {rmsle_rf_ts_log:.6f}")
print(f"HGBRT + no FE, TS split, raw : {rmsle_hgbr_ts_raw:.6f}")
print(f"HGBRT + no FE, TS split, log : {rmsle_hgbr_ts_log:.6f}")
print(f"GBRT + no FE, TS split, raw : {rmsle_gbr_ts_raw:.6f}")
print(f"GBRT + no FE, TS split, log : {rmsle_gbr_ts_log:.6f}")
print(f"XGB + no FE, TS split, raw : {rmsle_xgb_ts_raw:.6f}")
print(f"XGB + no FE, TS split, log : {rmsle_xgb_ts_log:.6f}")
print(f"CAT + no FE, TS split, raw : {rmsle_cbr_ts_raw:.6f}")
print(f"CAT + no FE, TS split, log : {rmsle_cbr_ts_log:.6f}")
print(f"LGBM + no FE, TS split, raw : {rmsle_lgbm_ts_raw:.6f}")
print(f"LGBM + no FE, TS split, log : {rmsle_lgbm_ts_log:.6f}")
print()



##########################################
# 3.2.8) Evaluate our pipeline with feature engineering but without autoregressive features
##########################################
# Raw pipeline without log-transform, with FE (no autoregressive FE)
pipe_rf_fe_raw = Pipeline([ # rf
    ('fe'  , BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', rf)
])
pipe_hgbr_fe_raw = Pipeline([ # hgbr
    ('fe'   , BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', hgbr)
])
pipe_gbr_fe_raw = Pipeline([ # gbr
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', gbr)
])
pipe_xgb_fe_raw = Pipeline([ # xgb
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', xgb)
])
pipe_cbr_fe_raw = Pipeline([ # catboost
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', cbr)
])
pipe_lgbm_fe_raw = Pipeline([ # lightgbm
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', lgbm)
])
##########################################
# Pipeline with log-transform and back, with FE (no autoregressive FE)
pipe_rf_fe_logtransf = Pipeline([ # rf
    ('fe'  , BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor    = rf,
        func         = np.log1p,
        inverse_func = np.expm1))
])
pipe_fe_hgbr_logtransf = Pipeline([ # hgbr
    ('fe'   , BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor    = hgbr,
        func         = np.log1p,
        inverse_func = np.expm1))
])
pipe_gbr_fe_logtransf = Pipeline([
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor=gbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_xgb_fe_logtransf = Pipeline([
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor=xgb, func=np.log1p, inverse_func=np.expm1))
])
pipe_cbr_fe_logtransf = Pipeline([
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor=cbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_lgbm_fe_logtransf = Pipeline([
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor=lgbm, func=np.log1p, inverse_func=np.expm1))
])
rmsle_rf_fe_last30_raw = eval_pipeline(pipe_rf_fe_raw, X, y, cv_last30)
rmsle_rf_fe_last30_log = eval_pipeline(pipe_rf_fe_logtransf, X, y, cv_last30)
rmsle_rf_fe_ts_raw = eval_pipeline(pipe_rf_fe_raw, X, y, cv_ts_no)
rmsle_rf_fe_ts_log = eval_pipeline(pipe_rf_fe_logtransf, X, y, cv_ts_no)
rmsle_fe_hgbr_last30_raw = eval_pipeline(pipe_hgbr_fe_raw, X, y, cv_last30)
rmsle_fe_hgbr_last30_log = eval_pipeline(pipe_fe_hgbr_logtransf, X, y, cv_last30)
rmsle_fe_hgbr_ts_raw     = eval_pipeline(pipe_hgbr_fe_raw, X, y, cv_ts_no)
rmsle_fe_hgbr_ts_log     = eval_pipeline(pipe_fe_hgbr_logtransf, X, y, cv_ts_no)
rmsle_gbr_fe_last30_raw = eval_pipeline(pipe_gbr_fe_raw, X, y, cv_last30)
rmsle_gbr_fe_last30_log = eval_pipeline(pipe_gbr_fe_logtransf, X, y, cv_last30)
rmsle_gbr_fe_ts_raw     = eval_pipeline(pipe_gbr_fe_raw, X, y, cv_ts_no)
rmsle_gbr_fe_ts_log     = eval_pipeline(pipe_gbr_fe_logtransf, X, y, cv_ts_no)
rmsle_xgb_fe_last30_raw = eval_pipeline(pipe_xgb_fe_raw, X, y, cv_last30)
rmsle_xgb_fe_last30_log = eval_pipeline(pipe_xgb_fe_logtransf, X, y, cv_last30)
rmsle_xgb_fe_ts_raw     = eval_pipeline(pipe_xgb_fe_raw, X, y, cv_ts_no)
rmsle_xgb_fe_ts_log     = eval_pipeline(pipe_xgb_fe_logtransf, X, y, cv_ts_no)
rmsle_cbr_fe_last30_raw = eval_pipeline(pipe_cbr_fe_raw, X, y, cv_last30)
rmsle_cbr_fe_last30_log = eval_pipeline(pipe_cbr_fe_logtransf, X, y, cv_last30)
rmsle_cbr_fe_ts_raw     = eval_pipeline(pipe_cbr_fe_raw, X, y, cv_ts_no)
rmsle_cbr_fe_ts_log     = eval_pipeline(pipe_cbr_fe_logtransf, X, y, cv_ts_no)
rmsle_lgbm_fe_last30_raw = eval_pipeline(pipe_lgbm_fe_raw, X, y, cv_last30)
rmsle_lgbm_fe_last30_log = eval_pipeline(pipe_lgbm_fe_logtransf, X, y, cv_last30)
rmsle_lgbm_fe_ts_raw     = eval_pipeline(pipe_lgbm_fe_raw, X, y, cv_ts_no)
rmsle_lgbm_fe_ts_log     = eval_pipeline(pipe_lgbm_fe_logtransf, X, y, cv_ts_no)
print(f"RF + FE (no AR), Last30 split, raw : {rmsle_rf_fe_last30_raw:.6f}")
print(f"RF + FE (no AR), Last30 split, log : {rmsle_rf_fe_last30_log:.6f}")
print(f"HGBRT + FE (no AR), Last30 split, raw : {rmsle_fe_hgbr_last30_raw:.6f}")
print(f"HGBRT + FE (no AR), Last30 split, log : {rmsle_fe_hgbr_last30_log:.6f}")
print(f"GBRT + FE (no AR), Last30 split, raw : {rmsle_gbr_fe_last30_raw:.6f}")
print(f"GBRT + FE (no AR), Last30 split, log : {rmsle_gbr_fe_last30_log:.6f}")
print(f"XGB + FE (no AR), Last30 split, raw : {rmsle_xgb_fe_last30_raw:.6f}")
print(f"XGB + FE (no AR), Last30 split, log : {rmsle_xgb_fe_last30_log:.6f}")
print(f"CAT + FE (no AR), Last30 split, raw : {rmsle_cbr_fe_last30_raw:.6f}")
print(f"CAT + FE (no AR), Last30 split, log : {rmsle_cbr_fe_last30_log:.6f}")
print(f"LGBM + FE (no AR), Last30 split, raw : {rmsle_lgbm_fe_last30_raw:.6f}")
print(f"LGBM + FE (no AR), Last30 split, log : {rmsle_lgbm_fe_last30_log:.6f}")
print(f"RF + FE (no AR), TS split, raw : {rmsle_rf_fe_ts_raw:.6f}")
print(f"RF + FE (no AR), TS split, log : {rmsle_rf_fe_ts_log:.6f}")
print(f"HGBRT + FE (no AR), TS split, raw : {rmsle_fe_hgbr_ts_raw:.6f}")
print(f"HGBRT + FE (no AR), TS split, log : {rmsle_fe_hgbr_ts_log:.6f}")
print(f"GBRT + FE (no AR), TS split, raw : {rmsle_gbr_fe_ts_raw:.6f}")
print(f"GBRT + FE (no AR), TS split, log : {rmsle_gbr_fe_ts_log:.6f}")
print(f"XGB + FE (no AR), TS split, raw : {rmsle_xgb_fe_ts_raw:.6f}")
print(f"XGB + FE (no AR), TS split, log : {rmsle_xgb_fe_ts_log:.6f}")
print(f"CAT + FE (no AR), TS split, raw : {rmsle_cbr_fe_ts_raw:.6f}")
print(f"CAT + FE (no AR), TS split, log : {rmsle_cbr_fe_ts_log:.6f}")
print(f"LGBM + FE (no AR), TS split, raw : {rmsle_lgbm_fe_ts_raw:.6f}")
print(f"LGBM + FE (no AR), TS split, log : {rmsle_lgbm_fe_ts_log:.6f}")
print()

##########################################
# 3.2.9) Evaluate our pipeline with feature engineering including autoregressive features
##########################################
# Raw pipeline without log-transform, with FE (including autoregressive FE)
pipe_rf_fe_ar_raw = Pipeline([ # rf
    ('fe'  , BikeFeatureEngineer()),
    ('model', rf)
])
pipe_fe_ar_hgbr_raw = Pipeline([ # hgbr
    ('fe'   , BikeFeatureEngineer()),
    ('model', hgbr)
])
pipe_gbr_fe_ar_raw = Pipeline([ # gbr
    ('fe', BikeFeatureEngineer()),
    ('model', gbr)
])
pipe_xgb_fe_ar_raw = Pipeline([ # xgb
    ('fe', BikeFeatureEngineer()),
    ('model', xgb)
])
pipe_cbr_fe_ar_raw = Pipeline([ # catboost
    ('fe', BikeFeatureEngineer()),
    ('model', cbr)
])
pipe_lgbm_fe_ar_raw = Pipeline([ # lightgbm
    ('fe', BikeFeatureEngineer()),
    ('model', lgbm)
])
##########################################
# Pipeline with log-transform and back, with FE (including autoregressive FE)
pipe_rf_fe_ar_logtransf = Pipeline([ # rf
    ('fe'  , BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor    = rf,
        func         = np.log1p,
        inverse_func = np.expm1))
])
pipe_fe_ar_hgbr_logtransf = Pipeline([ # hgbr
    ('fe'   , BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor    = hgbr,
        func         = np.log1p,
        inverse_func = np.expm1))
])
pipe_gbr_fe_ar_logtransf = Pipeline([ # gbr
    ('fe', BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor=gbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_xgb_fe_ar_logtransf = Pipeline([ # xgb
    ('fe', BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor=xgb, func=np.log1p, inverse_func=np.expm1))
])
pipe_cbr_fe_ar_logtransf = Pipeline([ # catboost
    ('fe', BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor=cbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_lgbm_fe_ar_logtransf = Pipeline([ # lightgbm
    ('fe', BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor=lgbm, func=np.log1p, inverse_func=np.expm1))
])
rmsle_rf_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_rf_fe_ar_raw, X, y, cv_last30)
rmsle_rf_fe_ar_last30_log = eval_pipeline_walkforward(pipe_rf_fe_ar_logtransf, X, y, cv_last30)
rmsle_rf_fe_ar_ts_raw = eval_pipeline_walkforward(pipe_rf_fe_ar_raw, X, y, cv_ts_ar)
rmsle_rf_fe_ar_ts_log = eval_pipeline_walkforward(pipe_rf_fe_ar_logtransf, X, y, cv_ts_ar)
rmsle_fe_ar_hgbr_last30_raw = eval_pipeline_walkforward(pipe_fe_ar_hgbr_raw, X, y, cv_last30)
rmsle_fe_ar_hgbr_last30_log = eval_pipeline_walkforward(pipe_fe_ar_hgbr_logtransf, X, y, cv_last30)
rmsle_fe_ar_hgbr_ts_raw     = eval_pipeline_walkforward(pipe_fe_ar_hgbr_raw, X, y, cv_ts_ar)
rmsle_fe_ar_hgbr_ts_log     = eval_pipeline_walkforward(pipe_fe_ar_hgbr_logtransf, X, y, cv_ts_ar)
rmsle_gbr_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_gbr_fe_ar_raw, X, y, cv_last30)
rmsle_gbr_fe_ar_last30_log = eval_pipeline_walkforward(pipe_gbr_fe_ar_logtransf, X, y, cv_last30)
rmsle_gbr_fe_ar_ts_raw     = eval_pipeline_walkforward(pipe_gbr_fe_ar_raw, X, y, cv_ts_ar)
rmsle_gbr_fe_ar_ts_log     = eval_pipeline_walkforward(pipe_gbr_fe_ar_logtransf, X, y, cv_ts_ar)
rmsle_xgb_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_xgb_fe_ar_raw, X, y, cv_last30)
rmsle_xgb_fe_ar_last30_log = eval_pipeline_walkforward(pipe_xgb_fe_ar_logtransf, X, y, cv_last30)
rmsle_xgb_fe_ar_ts_raw     = eval_pipeline_walkforward(pipe_xgb_fe_ar_raw, X, y, cv_ts_ar)
rmsle_xgb_fe_ar_ts_log     = eval_pipeline_walkforward(pipe_xgb_fe_ar_logtransf, X, y, cv_ts_ar)
rmsle_cbr_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_cbr_fe_ar_raw, X, y, cv_last30)
rmsle_cbr_fe_ar_last30_log = eval_pipeline_walkforward(pipe_cbr_fe_ar_logtransf, X, y, cv_last30)
rmsle_cbr_fe_ar_ts_raw     = eval_pipeline_walkforward(pipe_cbr_fe_ar_raw, X, y, cv_ts_ar)
rmsle_cbr_fe_ar_ts_log     = eval_pipeline_walkforward(pipe_cbr_fe_ar_logtransf, X, y, cv_ts_ar)
rmsle_lgbm_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_lgbm_fe_ar_raw, X, y, cv_last30)
rmsle_lgbm_fe_ar_last30_log = eval_pipeline_walkforward(pipe_lgbm_fe_ar_logtransf, X, y, cv_last30)
rmsle_lgbm_fe_ar_ts_raw     = eval_pipeline_walkforward(pipe_lgbm_fe_ar_raw, X, y, cv_ts_ar)
rmsle_lgbm_fe_ar_ts_log     = eval_pipeline_walkforward(pipe_lgbm_fe_ar_logtransf, X, y, cv_ts_ar)
print(f"RF + FE (with AR), Last30 split, raw : {rmsle_rf_fe_ar_last30_raw:.6f}")
print(f"RF + FE (with AR), Last30 split, log : {rmsle_rf_fe_ar_last30_log:.6f}")
print(f"HGBRT + FE (with AR), Last30 split, raw : {rmsle_fe_ar_hgbr_last30_raw:.6f}")
print(f"HGBRT + FE (with AR), Last30 log : {rmsle_fe_ar_hgbr_last30_log:.6f}")
print(f"GBRT + FE (with AR), Last30 split, raw : {rmsle_gbr_fe_ar_last30_raw:.6f}")
print(f"GBRT + FE (with AR), Last30 split, log : {rmsle_gbr_fe_ar_last30_log:.6f}")
print(f"XGB + FE (with AR), Last30 split, raw : {rmsle_xgb_fe_ar_last30_raw:.6f}")
print(f"XGB + FE (with AR), Last30 split, log : {rmsle_xgb_fe_ar_last30_log:.6f}")
print(f"CAT + FE (with AR), Last30 split, raw : {rmsle_cbr_fe_ar_last30_raw:.6f}")
print(f"CAT + FE (with AR), Last30 split, log : {rmsle_cbr_fe_ar_last30_log:.6f}")
print(f"LGBM + FE (with AR), Last30 split, raw : {rmsle_lgbm_fe_ar_last30_raw:.6f}")
print(f"LGBM + FE (with AR), Last30 split, log : {rmsle_lgbm_fe_ar_last30_log:.6f}")
print(f"RF + FE (with AR), TS split, raw : {rmsle_rf_fe_ar_ts_raw:.6f}")
print(f"RF + FE (with AR), TS split, log : {rmsle_rf_fe_ar_ts_log:.6f}")
print(f"HGBRT + FE (with AR),  TS   raw : {rmsle_fe_ar_hgbr_ts_raw:.6f}")
print(f"HGBRT + FE (with AR),  TS   log : {rmsle_fe_ar_hgbr_ts_log:.6f}")
print(f"GBRT + FE (with AR), TS split, raw : {rmsle_gbr_fe_ar_ts_raw:.6f}")
print(f"GBRT + FE (with AR), TS split, log : {rmsle_gbr_fe_ar_ts_log:.6f}")
print(f"XGB + FE (with AR), TS split, raw : {rmsle_xgb_fe_ar_ts_raw:.6f}")
print(f"XGB + FE (with AR), TS split, log : {rmsle_xgb_fe_ar_ts_log:.6f}")
print(f"CAT + FE (with AR), TS split, raw : {rmsle_cbr_fe_ar_ts_raw:.6f}")
print(f"CAT + FE (with AR), TS split, log : {rmsle_cbr_fe_ar_ts_log:.6f}")
print(f"LGBM + FE (with AR), TS split, raw : {rmsle_lgbm_fe_ar_ts_raw:.6f}")
print(f"LGBM + FE (with AR), TS split, log : {rmsle_lgbm_fe_ar_ts_log:.6f}")
print()

##########################################
# 3.2.10) Diagnostics: multicollinearity on engineered features (TRAIN ONLY)
##########################################
# Why train-only: avoid peeking at the test distribution and keep diagnostics fold-consistent. Use TSS per sklearn docs. 
# (TimeSeriesSplit is the correct CV for ordered data; 'gap' protects AR features.)  # refs: sklearn TSS docs
# Helper: VIF
def compute_vif(df: pd.DataFrame) -> pd.DataFrame:
    Xn = df.select_dtypes(include=[np.number]).copy()
    # add intercept for OLS-style VIF computation
    Xn.insert(0, "_intercept", 1.0)
    vifs = []
    A = Xn.to_numpy()
    cols = Xn.columns.tolist()
    for j, col in enumerate(cols[1:], start=1):  # skip intercept at 0
        yj = A[:, j]
        Xj = np.delete(A, j, axis=1)
        r2 = LinearRegression(fit_intercept=False).fit(Xj, yj).score(Xj, yj)
        # guard against numerical 1.0
        vif = np.inf if r2 >= 1 - 1e-12 else 1.0 / (1.0 - r2)
        vifs.append((col, float(vif)))
    return pd.DataFrame(vifs, columns=["feature", "VIF"]).sort_values("VIF", ascending=False)

def diagnose_multicollinearity(add_lag1: bool, add_roll7: bool, cv):
    """
    Build engineered TRAIN matrix for one fold, then:
      1) plot correlation heatmap
      2) print top VIFs
    """
    tr_idx, _ = next(cv.split(X))                     # first fold, TRAIN ONLY
    X_tr = X.iloc[tr_idx].copy()

    fe = BikeFeatureEngineer(add_lag1=add_lag1, add_roll7=add_roll7)
    fe_fit = clone(fe).fit(X_tr)                      # fit FE on train
    Z_tr = fe_fit.transform(X_tr)                     # engineered train design matrix

    # 1) Correlation heatmap (pairwise) with annotations and upper-triangle mask
    corr = Z_tr.corr(numeric_only=True)
    mask = np.triu(np.ones_like(corr, dtype=bool), k=1)  # hide upper triangle
    fig, ax = plt.subplots(figsize=(12, 9))
    sns.heatmap(
        corr, mask=mask, cmap="vlag", center=0, vmin=-1, vmax=1,
        square=True, linewidths=.5, linecolor='white',
        annot=True, fmt=".2f", annot_kws={"size":8}, ax=ax
    )
    ax.set_title(f"Post-FE correlations (train-only). AR: lag1={add_lag1}, roll7={add_roll7}")
    plt.tight_layout()
    savefig_pdf(f"fig_corr_train_only_AR_{add_lag1}_{add_roll7}", FIGDIR, fig)


    # 2) VIF (multivariate collinearity)
    vif_df = compute_vif(Z_tr)
    print("Top VIFs (train-only):")
    print(vif_df.head(20).to_string(index=False))
    return vif_df

# Run diagnostics for both settings you evaluate with CV
print("\n=== Multicollinearity diagnostics: NO AR features ===")
vif_no_ar  = diagnose_multicollinearity(add_lag1=False, add_roll7=False, cv=cv_ts_no)

print("\n=== Multicollinearity diagnostics: WITH AR features ===")
vif_with_ar = diagnose_multicollinearity(add_lag1=True,  add_roll7=True,  cv=cv_ts_ar)




"""# Potential improvements
-   Hyperparameter tuning of the RF
-   Add more features:
  - autoregressive: rolling mean instead of median, or as well as rolling median; lag-based feature, not only computed from `cnt` but also from `casual` and `registered`(if not heavily correlated with `cnt`)
  - weather: "pleasant_weather", for example if temp > 0.5 and hum < 0.6. For this, I would read in detail the paper that created the UCI dataset, plus articles on how weather and bike rental forecasts are related, etc.
- Explore feature importance
- Try new models
  - Gradient-boosted trees: they keep learning from the errors of previous trees, thus reducing bias and capturing subtler patterns than an RF, which just averages many independent trees
  - Time-series specific (maybe, if not even GBT works?): something like Prophet? Would need further exploration...
- The dataset is very tiny so the model might not be learning a lot: try retraining after gathering more data

## References

[1] Lichman, M. (2013). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.
"""
