# -*- coding: utf-8 -*-
"""bike-sharing-solution-day.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QDmH8wnLUJ_ME-iGB14WYL6rZIuQo-lw

# Kaggle's "Bike sharing demand" challenge

## Introduction

In this test task you will have an opportunity to demonstrate your skills of a Data Scientist from various angles - processing data, analyzing and visualizing it, finding insights, applying predictive techniques and explaining your reasoning about it.

The task is based around a bike sharing dataset openly available at UCI Machine Learning Repository [1].

Please go through the steps below, build up the necessary code and comment on your choices.

## Part 1 - Data Loading and Environment Preparation

**Tasks:**
1. Prepare a Python 3 virtual environment (with virtualenv command). `requirements.txt` output of `pip freeze` command should be included as part of your submission.
2. Load the data from UCI Repository and put it into the same folder with the notebook. The link to it is https://archive.ics.uci.edu/ml/datasets/bike+sharing+dataset . Here is an available mirror in case the above website is down: https://data.world/uci/bike-sharing-dataset
3. We split the data into two parts. One dataset containing the last 30 days and one dataset with the rest.
"""

##########################################
# 1.2)  Load the data from UCI Repository and put it into the same folder with the notebook.
"""
# Create `data` directory, if it doesn't exist
!mkdir -p data

# Download the zipped archive from UCI
!wget -q --show-progress -P data http://archive.ics.uci.edu/ml/machine-learning-databases/00275/Bike-Sharing-Dataset.zip

# Unzip to get `hour.csv`, `day.csv`, `Readme.txt`
!unzip -q data/Bike-Sharing-Dataset.zip -d data
"""
##########################################
# IMPORTS
##########################################
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use('Agg')   # non-GUI backend, safe for headless scripts
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import (
    RandomForestRegressor,
    HistGradientBoostingRegressor,
    GradientBoostingRegressor,
    )
from sklearn.base import clone
from sklearn.compose import TransformedTargetRegressor
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from pathlib import Path
FIGDIR = Path.cwd() / "plots" # save all figures under ./plots
FIGDIR.mkdir(parents=True, exist_ok=True) # create the folder if missing


from utils import savefig_pdf
from eda_utils import iqr_mask
from ml_utils import _rmsle, rmsle_scorer, make_timeseries_split, Last30DaysSplit, BikeFeatureEngineer, make_no_fe_preprocess
from model_eval import eval_pipeline, eval_pipeline_walkforward, ar_baseline_scores
from models import make_model

"""## Part 2 - Data Processing and Analysis

**Tasks:**
1. Perform all needed steps to load and clean the data. Please comment the major steps of your code.
2. Visualise rentals of bikes per day.
3. Assume that each bike has exactly maximum 12 rentals per day.
    * Find the maximum number of bicycles `nmax` that was needed in any one day.
    * Find the 95%-percentile of bicycles `n95` that was needed in any one day.
5. Visualize the distribution of the covered days depending on the number of available bicycles (e.g. `nmax` bicycles would cover 100% of days, `n95` covers 95%, etc.)

"""

##########################################
# 2.1)  Perform all needed steps to load and clean data. Please comment the major steps of your code.
##########################################
# 2.1.1) Read raw data
day_df = pd.read_csv('data/day.csv')
print(f"Daily dataset: {day_df.shape[0]} rows x {day_df.shape[1]} cols\n")
print(f"Its columns are {day_df.columns.values}")
print(f'Raw data: {day_df.head(2)}')
print()


input()

"""### Remarks about the cell below
Instead of dropping `casual` and `registered`, one could, alternatively:
1. train two separate models, one to predict `registered` and the other one to predict `casual`;
2. then, sum the two predictions to yield `cnt`

Pros: potentially better adaptability.
Cons:
- double training time. This might be negligible for decision trees, but this depend on their size (e.g. number of estimators) or training criteria (e.g.impurity criterion)
- prediction errors might add up more than by just predicting the single target `cnt`
"""

##########################################
# 2.1.2) No missing values by assumption
##########################################
# 2.1.3) Create new index and drop uninformative and leaking columns
day_df['date'] = pd.to_datetime(day_df['dteday']) # Create new column from 'dteday' with datetime format
day_df.set_index('date', inplace=True) # 'date' is unique ID -> set as DataFrame index
# Drop 'instant' (just an ID), 'dteday' (now redundant), 'casual' and 'registered' (risk of target leakage)
day_df = day_df.drop(columns=['instant', 'dteday', 'casual', 'registered'])
print(f'Columns after dropping uninformative and leaky ones: {day_df.columns}')
print()
# Statistics
print(day_df.describe())
print()

"""### Remarks about the cell below
- the `iqr_mask()` function could be computed with Pandas' `quantile([0.25, 0.75])` as well
- the only column with a seemingly weird value seems to be `hum`, with a row being `0.0`: Washington is rearely so dry. Outlier flag!

"""

##########################################
# 2.1.4) Outlier detection
print()
iqr_mask(day_df['hum'], 25, 75, 1.5)
# Replace outlier with humidity value from previous day
outlier_humidity_mask = day_df['hum'] == 0
day_df.loc[outlier_humidity_mask, 'hum'] = day_df['hum'].shift(1)[outlier_humidity_mask]
print()

##########################################
# 2.2)  Visualize rentals of bikes per day
##########################################
# 2.2.1) plot mean, rentals and rolling rentals
mean_cnt = day_df['cnt'].mean()
window = 30
# `center=True` centers the rolling window (instead of right aligned)
rolling_mean = day_df['cnt'].rolling(window=window, center=True).mean()
plt.figure(figsize=(12, 6))
# alpha sets some transparency for the daily count curve
plt.plot(day_df.index, day_df['cnt'], label='Daily count', alpha=0.5)
plt.plot(day_df.index, rolling_mean, label=f'{window}-day rolling mean', linewidth=2)
plt.axhline(mean_cnt, color='red', linestyle='--', linewidth=2, label=f'Mean = {mean_cnt:.0f}')
plt.title('Daily bike rentals')
plt.xlabel('Date')
plt.ylabel('Count')
plt.legend()
plt.tight_layout()
savefig_pdf("fig_daily_rentals", FIGDIR)

"""### Remarks about the two cells below
- The distribution is almost normal-like. However...
- ...multimodality detected (3 peaks/clusters): potentially corresponding to 3 seasons? (maybe winter, summer, shoulder season);
- Presence of some extreme lows/highs, which might be outliers, or not: they could correspond to extremely pleasant days, or very snowy days. Below I applied the Tukey's IQR rule to exclude potential outliers. I found basically no outliers. The extreme points probably correspond to exceptionally bad or good weather days
- log-transform is left-skewed (log compresses high values and sparsifies small ones)
"""

##########################################
# 2.2.2) Plot marginal distribution (histogram bars and related KDE) of `cnt`
sns.histplot(day_df['cnt'], bins=30, kde=True, kde_kws={'bw_adjust':0.7})
plt.title('Distribution of Daily Bike Rentals')
plt.xlabel('Daily rentals (cnt)')
plt.ylabel('Frequency')
plt.tight_layout()
savefig_pdf("fig_hist_cnt", FIGDIR)
# sns.pairplot(day_df)
##########################################
# 2.2.3) Plot marginal distribution (histogram bars and related KDE) of `cnt` *after* log-transform
transformed = np.log1p(day_df['cnt'])
sns.histplot(transformed, bins=30, kde=True, kde_kws={'bw_adjust':0.7})
plt.title('Distribution of Daily Bike Rentals (post log-transf.)')
plt.xlabel('Daily rentals (cnt)')
plt.ylabel('Frequency')
plt.tight_layout()
savefig_pdf("fig_hist_log_cnt", FIGDIR)

##########################################
# 2.2.4) Outlier detection and elimination
# traditional outlier range
iqr_mask(day_df['cnt'], 25, 75, 1.5)
# loosened outlier range
iqr_mask(day_df['cnt'], 25, 75, 1.0)

"""### Remarks about the cell below
It doesn't look like `weekday` should have a large predictive power, as a feature. Later, I tried removing it and training RFs without it. Since it improves the error, although very marginally, I decided to keep it
"""

##########################################
# 2.2.5) Visualize total bike rental count per weekday
plot_day_df = day_df.copy() # Add readable weekday column
plot_day_df['day_of_week'] = plot_day_df.index.day_name()
# Displayed names, ordered
dow_order = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
plt.figure(figsize=(10,5))
sns.barplot(
    data = plot_day_df,
    x = 'day_of_week',
    y = 'cnt',
    estimator = sum, # aggregate by sum of rentals
    order = dow_order, # keep calendar order
    hue='day_of_week',
    dodge=False, # avoid side-by-side bars
    # legend=False, # no legend needed since x-axis already labels
    palette = sns.color_palette("colorblind", 7)
)
plt.xlabel('Day of the week')
plt.ylabel('Total rentals (2011-2012)')
plt.title('Bike-sharing demand by weekday (sum over two years)')
plt.xticks(rotation=45)
plt.tight_layout()
savefig_pdf("fig_weekday_totals", FIGDIR)


##########################################
# 2.2.6) Visualize total bike rental count per  month
plot_day_df = day_df.copy() # Add readable month column
plot_day_df['month_name'] = plot_day_df.index.month_name()
# Displayed names, ordered
month_order = ['January','February','March','April','May','June',
               'July','August','September','October','November','December']
plt.figure(figsize=(12,5))
sns.barplot(
    data=plot_day_df,
    x='month_name',
    y='cnt',
    estimator=sum, # aggregate by sum of rentals
    order=month_order,
    hue='month_name',
    dodge=False,
    legend=False,
    palette=sns.color_palette("colorblind", 12)
)

plt.xlabel('Month')
plt.ylabel('Total rentals (2011-2012)')
plt.title('Bike-sharing demand by month (sum over two years)')
plt.xticks(rotation=45)
plt.tight_layout()
savefig_pdf("fig_month_totals", FIGDIR)


##########################################
# 2.2.7) Visualize total bike rental count per season
plot_day_df = day_df.copy()
season_map = {1: 'Spring', 2: 'Summer', 3: 'Fall', 4: 'Winter'} # Map numeric season codes to names
plot_day_df['season_name'] = plot_day_df['season'].map(season_map)
season_order = ['Spring', 'Summer', 'Fall', 'Winter'] # Displayed names, ordered
plt.figure(figsize=(8,5))
sns.barplot(
    data = plot_day_df,
    x = 'season_name',
    y = 'cnt',
    estimator = sum,
    order = season_order,
    hue='season_name',
    dodge=False,
    legend=False,
    palette = sns.color_palette("colorblind", 4)
)
plt.xlabel('Season')
plt.ylabel('Total rentals (2011-2012)')
plt.title('Bike-sharing demand by season (sum over two years)')
plt.tight_layout()
savefig_pdf("fig_season_totals", FIGDIR)


##########################################
# 2.2.8) Exploring multimodality in `cnt`: visualize distplot (KDE) and histplot (histograms)
# KDE for each season (smoothed estimated histogram distro): basically show PDF for each season
g = sns.displot(
    data=day_df.assign(season=day_df['season'].map(season_map)),
    x='cnt',
    hue='season',
    kind='kde',
    clip=(0, None),
    fill=False,
    common_norm=False,
    height=4,
    aspect=1.4
).set(title='Daily rental distribution by season')
g.savefig(FIGDIR / "fig_kde_by_season.pdf")  # FacetGrid has savefig
plt.close(g.fig)
# Histograms for each seasonal distribution
g = sns.FacetGrid(
        day_df.assign(season=day_df['season'].map(season_map)),
        col='season',
        col_wrap=2,
        height=3.2
    )
g.map(sns.histplot, 'cnt', bins=20, color='steelblue')
g.set_axis_labels('Daily rentals (cnt)', 'N. of days')
g.savefig(FIGDIR / "fig_hist_by_season.pdf")
plt.close(g.fig)

r"""### Remarks about the cell below
- `atemp` is so highly corr. with `temp` (0.99) that they are basically the same $\to$ drop
- `season` is highly corr. with `month` (0.83). However, since a) RFs don't suffer from highly correlated features that much, and b) I experimented with dropping `season` and this worsened the final test score $\to$ I decided to keep it
"""

##########################################
# 2.2.9) Visualize correlation matrix
print(day_df.columns)
corr = day_df[['season', 'yr', 'mnth', 'holiday', 'weekday', 'workingday',
       'weathersit', 'temp', 'atemp', 'hum', 'windspeed']].corr()
mask = np.array(corr)
mask[np.tril_indices_from(mask)] = False
fig, ax= plt.subplots()
fig.set_size_inches(20,10)
sns.heatmap(corr, mask=mask, vmax=.8, square=True, annot=True)
plt.tight_layout()
savefig_pdf("fig_corr_pre", FIGDIR, fig)

##########################################
# 2.3)  Assume that each bike has exactly maximum 12 rentals per day
# - Find the maximum number of bicycles nmax that was needed in any one day.
# - Find the 95%-percentile of bicycles n95 that was needed in any one day.
##########################################
# Compute the fleet size needed per day, assuming each bike is rented <=12 times daily (convert to int)
day_df['daily_fleet_size'] = np.ceil(day_df['cnt'] / 12).astype(int)
# Compute stats:
#   - `nmax`: fleet size needed to cover demand on "busiest" day
#   - `n95`: 95-th percentile fleet size on (smallest fleet inventory that would have covered 95% of days)
nmax = day_df['daily_fleet_size'].max()
n95  = int(np.ceil(np.percentile(day_df['daily_fleet_size'], 95)))
n50  = int(np.ceil(np.percentile(day_df['daily_fleet_size'], 50)))
print(f"Number of bikes needed on busiest day (nmax): {nmax}")
print(f"Smallest number of bikes to cover 95% of days (n95): {n95}")
print()

##########################################
# 2.4)  Visualize the distribution of the covered days depending on the number of available bicycles.
#       E.g. `nmax` bicycles would cover 100% of days, `n95` covers 95%, etc.
##########################################
# Build "coverage" curve. For every `daily_fleet_size` value k, compute proportion of days with demand <= k.
# Basically, compute empirical CDF (in %): P("bikes needed" <= k)) in [0,1]
coverage_df = (
    day_df['daily_fleet_size']
    .value_counts() # for each `daily_fleet_size` value k, count n. of days which required exactly k bikes (Series, indexed by k)
    .sort_index() # sort by bike count k (ascending)
    .cumsum() # running cumulative sum, represents days where <= k bikes needed
    / len(day_df) * 100 # convert into percentage ~CDF
    ).reset_index().rename(columns={'daily_fleet_size': 'k', 'count': 'emp_CDF'})
# Plot: needed fleet size `k` vs %of days covered `emp_CDF`
plt.figure(figsize=(10, 6))
# Empirical CDF is flat until a new value of k is attained, then jumps up:
#   - `plt.step`: draws that step-curve
#   - `where='post'`: means hold current CDF value until next x-tick (i.e., next CDF value is attained), then jump
plt.step(coverage_df['k'], coverage_df['emp_CDF'], where='post')
# Vertical dashed line at 50th, 95th and 100th (max) percentiles of fleet size
plt.axvline(n50, linestyle='--', label=f'n50 = {n50}', color='#0072B2')
plt.axvline(n95, linestyle='--', label=f'n95 = {n95}', color='#D55E00')
plt.axvline(nmax, linestyle='--', label=f'nmax = {nmax}', color='#009E73')
plt.xlabel('N. needed bicycles (k)')
plt.ylabel('% of fully served days (demand ≤ k)')
plt.title(f'Daily coverage for different bicycle fleet sizes k, over {len(day_df)} days')
plt.grid(True, linestyle=':') # light dotted grid
plt.legend()
plt.tight_layout()
savefig_pdf("fig_coverage_ecdf", FIGDIR)

"""## Part 3 - Building prediction models

**Tasks:**
1. Define a test metric for predicting the daily demand for bike sharing, which you would like to use to measure the accuracy of the constructed models, and explain your choice.
2. Build a demand prediction model with Random Forest, preferably making use of following python libraries: scikit-learn.
3. Report the value of the chosen test metric on the provided data.
"""

##########################################
# Data
X = day_df.copy(deep=True)
X = day_df.copy(deep=True).drop(columns=['daily_fleet_size'])
y = X['cnt']
print(f'Columns before any feature engineering: {X.columns.values}')
print()

r"""### 3.0) Feature engineering: log (Box-Cox) transform + revert
-   **Compresses outliers**, reducing their relative importance $\to$ now big and small rental days (e.g. vv hot or vv cold days) are comparable on an "additive scale", and additive effects should be more easily"measured"/"estimated" by models than multiplicative effect. So, our trees will tolerate more error on these outliers while being more accurate on the bulk of data.
-   **Var is more uniform/stabilized**, while not changing the ranking of the values $\to$ improved split-point detection in decision trees. What happens is that, in RFs, each tree make splits by minimizing the variance of the children (impurity-based); in the end, since the label/prediction at the leaves is a mean, on the leaves RF basically minimize the sum of variances. Now, if the target is skewed, outliers will affect the variances and worsen splits: split points are pushed towards the outliers, as a tree tries to "isolate" the tail from the remaining points $\to$ trees will be more affected by outliers if data is not transformed, i.e., they will predict outliers more accurately

See empirical performance at end, showcasing a superior performance with log-transform

### 3.1) Define a test metric for predicting the daily demand for bike sharing, which you would like to use to measure the accuracy of the constructed models, and explain your choice.

Chosen: Root Mean Squared Log Error (RMSLE): $\sqrt{\dfrac{1}{n}\sum_{i \in [n]}\Bigl(\log(\hat{y}_i+1) - \log(y_i+1)\Bigr)^2}$
- each summand in the loss is roughly equivalent to $≈\log^2\left(\dfrac{\hat{y_i}}{y_i}\right)$, with $\hat{y_i}$ a prediction and $y_i$ a label
- **asymmetric costs**: RMSLE yields a larger penalty for under-predictions: basically grows exponentially for underpredictions and less than logarithmically for overprediction. This is more useful than, say, MAE and MSE, which are "cost-symmetric" (no difference between under and over predictions). In fact, while over-predicting might not a big issue (e.g., if we prepared more bikes at a spot for one day, we could always move some during the night...or have them at the ready for the day after, the assumption being that people are always willing to move a bit to get to a bike), but under-predicting is bad because we cannot satisfy demand and thus lose money
- **robustness to outliers**: the log makes it robust to outliers, with similar considerations as the ones made about the log-transform. Useful considering that the data in `cnt` has a wide range of values (almost 3 orders of magnitude, from 22 to 8714). Also useful because it can predict relative errors well, and we are more interested in them than absolute errors (for instance, predicting 9 instead of 10 has the same RMSLE as predicting 900 instead of 1000).

### Remarks about the cells below
#### About Pipelines
I used sklearn's Pipelines used, so in the cells below I define some helper functions or classes that I will call in `eval_pipeline`, which
1. perform a train/test split $\to$ see `Month20tr10teSplit` and `Last30DaysSplit`
2. do feature engineering and potentially applies target transformation $\to$ see `preprocess` (applying no feature engineering), `one_hot_no_sparse` (setting up a one-hot encoder), `BikeFeatureEngineer`. This last one contains:
  - drop highly correlated features
  - compute cyclical sin/cos transformation features, important because they enforce continuity (e.g. Monday is close to Sunday)
  - optionally, add autoregressive features using past data: 1-day lag and 7-day rolling median. Note that this does not leak info and is feasible for production
3. fit a predictor, then evaluates it on a test set $\to$ see `eval_pipeline`

#### About splits
I use two splits: one with last 30 days as test set, and another with a time series split to avoid data leakage. I avoid random splits to prevent leaking future info.
"""

##########################################
# 3.2) Build a demand prediction model with Random Forest, preferably making use of following python libraries: scikit-learn.






##########################################
# 3.2.2) NO Feature engineering
# Build the passthrough preprocessor (no FE) from helper
preprocess, to_df, feat_cols = make_no_fe_preprocess(X, target_col='cnt')


##########################################
# 3.2.4) Pipeline evaluation
# Provided by `model_eval`: eval_pipeline, eval_pipeline_walkforward, ar_baseline_scores

# Instantiate splitters
cv_last30 = Last30DaysSplit()
cv_ts_ar  = make_timeseries_split(add_lag1=True,  add_roll7=True,  n_splits=5, test_size=30)
cv_ts_no  = make_timeseries_split(add_lag1=False, add_roll7=False, n_splits=5, test_size=30)

# Evaluate autoregressive baselines
lag1_30, roll7_30 = ar_baseline_scores(y, cv_last30, window=7)
lag1_ts, roll7_ts = ar_baseline_scores(y, cv_ts_ar,  window=7)
print(f'Last-30 split baseline (lag-1), RMSLE : {lag1_30:.6f}')
print(f'Last-30 split baseline (roll-7), RMSLE : {roll7_30:.6f}')
print(f'Time-series split baseline (lag-1), RMSLE : {lag1_ts:.6f}')
print(f'Time-series split baseline (roll-7), RMSLE : {roll7_ts:.6f}')
print()

##########################################
# 3.2.6) Our Base regressor and splitters
# Models are provided by `models.make_model`

hgbr = make_model("hgbr")
rf   = make_model("rf")
gbr  = make_model("gbr")
xgb  = make_model("xgb")
cbr  = make_model("cbr")
lgbm = make_model("lgbm")

r"""#### About test results (autoregressive baselines VS simple RF baseline)
- `cv_last30` split: autocorrelation is strong and, in a sense, bike rental demand is persistent to the 1-day lag. In fact:
  - the 1-day lag autoregressive baseline is good, actually better than our naive random forest with og-scaled target and no feature engineering. But already when we log-transform we are better than naive baseline, and then adding FE we improve even more.
  - note that our RF is better on this split when autoregressive feature are used WRT no AR features
- `cv_20_10` split: our RF is already better than the autoregressive baselines on this "more challenging split". Our calendar+weather RF improves once we stabilise variance (with log-target) and add basic feature engineering. Autoregressive features worsen the test scores. It would be interesting to perform experiments on a larger dataset
- the log-transform (transform `y_train`, then backtransform `y_pred` before computing the RMSLE) always yields better test results

#### Takeaways
- `cv_last30`: our best model (with feature engineering including autoregressive features, and target log-transform) reduces the 1-day lag baseline error by about $18\%$, and the 7-day rolling median baseline by about $33\%$.
- `cv_last30`: on this tougher split, our best model (with feature engineering not including autoregressive features, and target log-transform) reduces the 1-day lag baseline error by about $19\%$, and the 7-day rolling median baseline by about $14\%$.
- **log-transform**: always produces improvements in test error: at least $2\%$ and as much $16\%$ WRT un-transformed target
- **autoregressive features**: could be useful but to be verified with larger dataset
"""

##########################################
# 3.2.7) Evaluate our pipeline without feature engineering
##########################################
# Raw pipeline without log-transform
pipe_rf_raw = Pipeline([ # rf
    ('prep' , preprocess),
    ('model', rf)
])
pipe_hgbr_raw = Pipeline([ # hgbr
    ('prep' , preprocess),
    ('model', hgbr)
])
pipe_gbr_raw = Pipeline([ # gbr
    ('prep', preprocess),
    ('model', gbr)
])
pipe_xgb_raw = Pipeline([ # xgb
    ('prep', preprocess),
    ('model', xgb)
])
pipe_cbr_raw = Pipeline([ # catboost
    ('prep', preprocess),
    ('model', cbr)
])
pipe_lgbm_raw = Pipeline([ # lightgbm
    ('prep', preprocess),
    ('to_df', to_df),
    ('model', lgbm)
])
##########################################
# Pipeline with log-transform and back
pipe_rf_logtransf = Pipeline([ # rf
    ('prep' , preprocess),
    ('model', TransformedTargetRegressor(
        regressor = rf,
        func = np.log1p,   # log-transform `y_train`
        inverse_func = np.expm1)) # revert `y_pred` to og scale to compute RMSLE
])
pipe_hgbr_logtransf = Pipeline([ # hgbr
    ('prep' , preprocess),
    ('model', TransformedTargetRegressor(
        regressor = hgbr,
        func = np.log1p,
        inverse_func = np.expm1))
])
pipe_gbr_logtransf = Pipeline([ # gbr
    ('prep', preprocess),
    ('model', TransformedTargetRegressor(
        regressor=gbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_xgb_logtransf = Pipeline([ # xgb
    ('prep', preprocess),
    ('model', TransformedTargetRegressor(
        regressor=xgb, func=np.log1p, inverse_func=np.expm1))
])
pipe_lgbm_logtransf = Pipeline([ # lightgbm
    ('prep', preprocess), # your passthrough by names
    ('to_df', to_df), # keep names for downstream estimator
    ('model', TransformedTargetRegressor(
        regressor=lgbm, func=np.log1p, inverse_func=np.expm1))
])
rmsle_xgb_last30_raw = eval_pipeline(pipe_xgb_raw, X, y, cv_last30)
rmsle_xgb_last30_log = eval_pipeline(pipe_xgb_logtransf, X, y, cv_last30)
rmsle_xgb_ts_raw     = eval_pipeline(pipe_xgb_raw, X, y, cv_ts_no)
rmsle_xgb_ts_log     = eval_pipeline(pipe_xgb_logtransf, X, y, cv_ts_no)
pipe_cbr_logtransf = Pipeline([ # catboost
    ('prep', preprocess),
    ('model', TransformedTargetRegressor(
        regressor=cbr, func=np.log1p, inverse_func=np.expm1))
])
rmsle_cbr_last30_raw = eval_pipeline(pipe_cbr_raw, X, y, cv_last30)
rmsle_cbr_last30_log = eval_pipeline(pipe_cbr_logtransf, X, y, cv_last30)
rmsle_cbr_ts_raw     = eval_pipeline(pipe_cbr_raw, X, y, cv_ts_no)
rmsle_cbr_ts_log     = eval_pipeline(pipe_cbr_logtransf, X, y, cv_ts_no)
rmsle_rf_last30_raw = eval_pipeline(pipe_rf_raw, X, y, cv_last30)
rmsle_rf_last30_log = eval_pipeline(pipe_rf_logtransf, X, y, cv_last30)
rmsle_rf_ts_raw = eval_pipeline(pipe_rf_raw, X, y, cv_ts_no)
rmsle_rf_ts_log = eval_pipeline(pipe_rf_logtransf, X, y, cv_ts_no)
rmsle_hgbr_last30_raw = eval_pipeline(pipe_hgbr_raw, X, y, cv_last30)
rmsle_hgbr_last30_log = eval_pipeline(pipe_hgbr_logtransf, X, y, cv_last30)
rmsle_hgbr_ts_raw     = eval_pipeline(pipe_hgbr_raw, X, y, cv_ts_no)
rmsle_hgbr_ts_log     = eval_pipeline(pipe_hgbr_logtransf, X, y, cv_ts_no)
rmsle_gbr_last30_raw = eval_pipeline(pipe_gbr_raw, X, y, cv_last30)
rmsle_gbr_last30_log = eval_pipeline(pipe_gbr_logtransf, X, y, cv_last30)
rmsle_gbr_ts_raw     = eval_pipeline(pipe_gbr_raw, X, y, cv_ts_no)
rmsle_gbr_ts_log     = eval_pipeline(pipe_gbr_logtransf, X, y, cv_ts_no)
rmsle_xgb_last30_raw = eval_pipeline(pipe_xgb_raw, X, y, cv_last30)
rmsle_xgb_last30_log = eval_pipeline(pipe_xgb_logtransf, X, y, cv_last30)
rmsle_xgb_ts_raw     = eval_pipeline(pipe_xgb_raw, X, y, cv_ts_no)
rmsle_xgb_ts_log     = eval_pipeline(pipe_xgb_logtransf, X, y, cv_ts_no)
rmsle_lgbm_last30_raw = eval_pipeline(pipe_lgbm_raw, X, y, cv_last30)
rmsle_lgbm_last30_log = eval_pipeline(pipe_lgbm_logtransf, X, y, cv_last30)
rmsle_lgbm_ts_raw     = eval_pipeline(pipe_lgbm_raw, X, y, cv_ts_no)
rmsle_lgbm_ts_log     = eval_pipeline(pipe_lgbm_logtransf, X, y, cv_ts_no)
print(f"RF + no FE Last30 split, raw : {rmsle_rf_last30_raw:.6f}")
print(f"RF + no FE, Last30 split, log : {rmsle_rf_last30_log:.6f}")
print(f"HGBRT + no FE, Last30 split, raw : {rmsle_hgbr_last30_raw:.6f}")
print(f"HGBRT + no FE, Last30 log, log : {rmsle_hgbr_last30_log:.6f}")
print(f"GBRT + no FE, Last30 split, raw : {rmsle_gbr_last30_raw:.6f}")
print(f"GBRT + no FE, Last30 split, log : {rmsle_gbr_last30_log:.6f}")
print(f"XGB + no FE, Last30 split, raw : {rmsle_xgb_last30_raw:.6f}")
print(f"XGB + no FE, Last30 split, log : {rmsle_xgb_last30_log:.6f}")
print(f"CAT + no FE, Last30 split, raw : {rmsle_cbr_last30_raw:.6f}")
print(f"CAT + no FE, Last30 split, log : {rmsle_cbr_last30_log:.6f}")
print(f"LGBM + no FE, Last30 split, raw : {rmsle_lgbm_last30_raw:.6f}")
print(f"LGBM + no FE, Last30 split, log : {rmsle_lgbm_last30_log:.6f}")
print(f"RF + no FE, TS split, raw : {rmsle_rf_ts_raw:.6f}")
print(f"RF + no FE, TS split, log : {rmsle_rf_ts_log:.6f}")
print(f"HGBRT + no FE, TS split, raw : {rmsle_hgbr_ts_raw:.6f}")
print(f"HGBRT + no FE, TS split, log : {rmsle_hgbr_ts_log:.6f}")
print(f"GBRT + no FE, TS split, raw : {rmsle_gbr_ts_raw:.6f}")
print(f"GBRT + no FE, TS split, log : {rmsle_gbr_ts_log:.6f}")
print(f"XGB + no FE, TS split, raw : {rmsle_xgb_ts_raw:.6f}")
print(f"XGB + no FE, TS split, log : {rmsle_xgb_ts_log:.6f}")
print(f"CAT + no FE, TS split, raw : {rmsle_cbr_ts_raw:.6f}")
print(f"CAT + no FE, TS split, log : {rmsle_cbr_ts_log:.6f}")
print(f"LGBM + no FE, TS split, raw : {rmsle_lgbm_ts_raw:.6f}")
print(f"LGBM + no FE, TS split, log : {rmsle_lgbm_ts_log:.6f}")
print()



##########################################
# 3.2.8) Evaluate our pipeline with feature engineering but without autoregressive features
##########################################
# Raw pipeline without log-transform, with FE (no autoregressive FE)
pipe_rf_fe_raw = Pipeline([ # rf
    ('fe'  , BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', rf)
])
pipe_hgbr_fe_raw = Pipeline([ # hgbr
    ('fe'   , BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', hgbr)
])
pipe_gbr_fe_raw = Pipeline([ # gbr
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', gbr)
])
pipe_xgb_fe_raw = Pipeline([ # xgb
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', xgb)
])
pipe_cbr_fe_raw = Pipeline([ # catboost
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', cbr)
])
pipe_lgbm_fe_raw = Pipeline([ # lightgbm
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', lgbm)
])
##########################################
# Pipeline with log-transform and back, with FE (no autoregressive FE)
pipe_rf_fe_logtransf = Pipeline([ # rf
    ('fe'  , BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor    = rf,
        func         = np.log1p,
        inverse_func = np.expm1))
])
pipe_fe_hgbr_logtransf = Pipeline([ # hgbr
    ('fe'   , BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor    = hgbr,
        func         = np.log1p,
        inverse_func = np.expm1))
])
pipe_gbr_fe_logtransf = Pipeline([
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor=gbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_xgb_fe_logtransf = Pipeline([
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor=xgb, func=np.log1p, inverse_func=np.expm1))
])
pipe_cbr_fe_logtransf = Pipeline([
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor=cbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_lgbm_fe_logtransf = Pipeline([
    ('fe', BikeFeatureEngineer(add_lag1=False, add_roll7=False)),
    ('model', TransformedTargetRegressor(
        regressor=lgbm, func=np.log1p, inverse_func=np.expm1))
])
rmsle_rf_fe_last30_raw = eval_pipeline(pipe_rf_fe_raw, X, y, cv_last30)
rmsle_rf_fe_last30_log = eval_pipeline(pipe_rf_fe_logtransf, X, y, cv_last30)
rmsle_rf_fe_ts_raw = eval_pipeline(pipe_rf_fe_raw, X, y, cv_ts_no)
rmsle_rf_fe_ts_log = eval_pipeline(pipe_rf_fe_logtransf, X, y, cv_ts_no)
rmsle_fe_hgbr_last30_raw = eval_pipeline(pipe_hgbr_fe_raw, X, y, cv_last30)
rmsle_fe_hgbr_last30_log = eval_pipeline(pipe_fe_hgbr_logtransf, X, y, cv_last30)
rmsle_fe_hgbr_ts_raw     = eval_pipeline(pipe_hgbr_fe_raw, X, y, cv_ts_no)
rmsle_fe_hgbr_ts_log     = eval_pipeline(pipe_fe_hgbr_logtransf, X, y, cv_ts_no)
rmsle_gbr_fe_last30_raw = eval_pipeline(pipe_gbr_fe_raw, X, y, cv_last30)
rmsle_gbr_fe_last30_log = eval_pipeline(pipe_gbr_fe_logtransf, X, y, cv_last30)
rmsle_gbr_fe_ts_raw     = eval_pipeline(pipe_gbr_fe_raw, X, y, cv_ts_no)
rmsle_gbr_fe_ts_log     = eval_pipeline(pipe_gbr_fe_logtransf, X, y, cv_ts_no)
rmsle_xgb_fe_last30_raw = eval_pipeline(pipe_xgb_fe_raw, X, y, cv_last30)
rmsle_xgb_fe_last30_log = eval_pipeline(pipe_xgb_fe_logtransf, X, y, cv_last30)
rmsle_xgb_fe_ts_raw     = eval_pipeline(pipe_xgb_fe_raw, X, y, cv_ts_no)
rmsle_xgb_fe_ts_log     = eval_pipeline(pipe_xgb_fe_logtransf, X, y, cv_ts_no)
rmsle_cbr_fe_last30_raw = eval_pipeline(pipe_cbr_fe_raw, X, y, cv_last30)
rmsle_cbr_fe_last30_log = eval_pipeline(pipe_cbr_fe_logtransf, X, y, cv_last30)
rmsle_cbr_fe_ts_raw     = eval_pipeline(pipe_cbr_fe_raw, X, y, cv_ts_no)
rmsle_cbr_fe_ts_log     = eval_pipeline(pipe_cbr_fe_logtransf, X, y, cv_ts_no)
rmsle_lgbm_fe_last30_raw = eval_pipeline(pipe_lgbm_fe_raw, X, y, cv_last30)
rmsle_lgbm_fe_last30_log = eval_pipeline(pipe_lgbm_fe_logtransf, X, y, cv_last30)
rmsle_lgbm_fe_ts_raw     = eval_pipeline(pipe_lgbm_fe_raw, X, y, cv_ts_no)
rmsle_lgbm_fe_ts_log     = eval_pipeline(pipe_lgbm_fe_logtransf, X, y, cv_ts_no)
print(f"RF + FE (no AR), Last30 split, raw : {rmsle_rf_fe_last30_raw:.6f}")
print(f"RF + FE (no AR), Last30 split, log : {rmsle_rf_fe_last30_log:.6f}")
print(f"HGBRT + FE (no AR), Last30 split, raw : {rmsle_fe_hgbr_last30_raw:.6f}")
print(f"HGBRT + FE (no AR), Last30 split, log : {rmsle_fe_hgbr_last30_log:.6f}")
print(f"GBRT + FE (no AR), Last30 split, raw : {rmsle_gbr_fe_last30_raw:.6f}")
print(f"GBRT + FE (no AR), Last30 split, log : {rmsle_gbr_fe_last30_log:.6f}")
print(f"XGB + FE (no AR), Last30 split, raw : {rmsle_xgb_fe_last30_raw:.6f}")
print(f"XGB + FE (no AR), Last30 split, log : {rmsle_xgb_fe_last30_log:.6f}")
print(f"CAT + FE (no AR), Last30 split, raw : {rmsle_cbr_fe_last30_raw:.6f}")
print(f"CAT + FE (no AR), Last30 split, log : {rmsle_cbr_fe_last30_log:.6f}")
print(f"LGBM + FE (no AR), Last30 split, raw : {rmsle_lgbm_fe_last30_raw:.6f}")
print(f"LGBM + FE (no AR), Last30 split, log : {rmsle_lgbm_fe_last30_log:.6f}")
print(f"RF + FE (no AR), TS split, raw : {rmsle_rf_fe_ts_raw:.6f}")
print(f"RF + FE (no AR), TS split, log : {rmsle_rf_fe_ts_log:.6f}")
print(f"HGBRT + FE (no AR), TS split, raw : {rmsle_fe_hgbr_ts_raw:.6f}")
print(f"HGBRT + FE (no AR), TS split, log : {rmsle_fe_hgbr_ts_log:.6f}")
print(f"GBRT + FE (no AR), TS split, raw : {rmsle_gbr_fe_ts_raw:.6f}")
print(f"GBRT + FE (no AR), TS split, log : {rmsle_gbr_fe_ts_log:.6f}")
print(f"XGB + FE (no AR), TS split, raw : {rmsle_xgb_fe_ts_raw:.6f}")
print(f"XGB + FE (no AR), TS split, log : {rmsle_xgb_fe_ts_log:.6f}")
print(f"CAT + FE (no AR), TS split, raw : {rmsle_cbr_fe_ts_raw:.6f}")
print(f"CAT + FE (no AR), TS split, log : {rmsle_cbr_fe_ts_log:.6f}")
print(f"LGBM + FE (no AR), TS split, raw : {rmsle_lgbm_fe_ts_raw:.6f}")
print(f"LGBM + FE (no AR), TS split, log : {rmsle_lgbm_fe_ts_log:.6f}")
print()

##########################################
# 3.2.9) Evaluate our pipeline with feature engineering including autoregressive features
##########################################
# Raw pipeline without log-transform, with FE (including autoregressive FE)
pipe_rf_fe_ar_raw = Pipeline([ # rf
    ('fe'  , BikeFeatureEngineer()),
    ('model', rf)
])
pipe_fe_ar_hgbr_raw = Pipeline([ # hgbr
    ('fe'   , BikeFeatureEngineer()),
    ('model', hgbr)
])
pipe_gbr_fe_ar_raw = Pipeline([ # gbr
    ('fe', BikeFeatureEngineer()),
    ('model', gbr)
])
pipe_xgb_fe_ar_raw = Pipeline([ # xgb
    ('fe', BikeFeatureEngineer()),
    ('model', xgb)
])
pipe_cbr_fe_ar_raw = Pipeline([ # catboost
    ('fe', BikeFeatureEngineer()),
    ('model', cbr)
])
pipe_lgbm_fe_ar_raw = Pipeline([ # lightgbm
    ('fe', BikeFeatureEngineer()),
    ('model', lgbm)
])
##########################################
# Pipeline with log-transform and back, with FE (including autoregressive FE)
pipe_rf_fe_ar_logtransf = Pipeline([ # rf
    ('fe'  , BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor    = rf,
        func         = np.log1p,
        inverse_func = np.expm1))
])
pipe_fe_ar_hgbr_logtransf = Pipeline([ # hgbr
    ('fe'   , BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor    = hgbr,
        func         = np.log1p,
        inverse_func = np.expm1))
])
pipe_gbr_fe_ar_logtransf = Pipeline([ # gbr
    ('fe', BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor=gbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_xgb_fe_ar_logtransf = Pipeline([ # xgb
    ('fe', BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor=xgb, func=np.log1p, inverse_func=np.expm1))
])
pipe_cbr_fe_ar_logtransf = Pipeline([ # catboost
    ('fe', BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor=cbr, func=np.log1p, inverse_func=np.expm1))
])
pipe_lgbm_fe_ar_logtransf = Pipeline([ # lightgbm
    ('fe', BikeFeatureEngineer()),
    ('model', TransformedTargetRegressor(
        regressor=lgbm, func=np.log1p, inverse_func=np.expm1))
])
rmsle_rf_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_rf_fe_ar_raw, X, y, cv_last30)
rmsle_rf_fe_ar_last30_log = eval_pipeline_walkforward(pipe_rf_fe_ar_logtransf, X, y, cv_last30)
rmsle_rf_fe_ar_ts_raw = eval_pipeline_walkforward(pipe_rf_fe_ar_raw, X, y, cv_ts_ar)
rmsle_rf_fe_ar_ts_log = eval_pipeline_walkforward(pipe_rf_fe_ar_logtransf, X, y, cv_ts_ar)
rmsle_fe_ar_hgbr_last30_raw = eval_pipeline_walkforward(pipe_fe_ar_hgbr_raw, X, y, cv_last30)
rmsle_fe_ar_hgbr_last30_log = eval_pipeline_walkforward(pipe_fe_ar_hgbr_logtransf, X, y, cv_last30)
rmsle_fe_ar_hgbr_ts_raw     = eval_pipeline_walkforward(pipe_fe_ar_hgbr_raw, X, y, cv_ts_ar)
rmsle_fe_ar_hgbr_ts_log     = eval_pipeline_walkforward(pipe_fe_ar_hgbr_logtransf, X, y, cv_ts_ar)
rmsle_gbr_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_gbr_fe_ar_raw, X, y, cv_last30)
rmsle_gbr_fe_ar_last30_log = eval_pipeline_walkforward(pipe_gbr_fe_ar_logtransf, X, y, cv_last30)
rmsle_gbr_fe_ar_ts_raw     = eval_pipeline_walkforward(pipe_gbr_fe_ar_raw, X, y, cv_ts_ar)
rmsle_gbr_fe_ar_ts_log     = eval_pipeline_walkforward(pipe_gbr_fe_ar_logtransf, X, y, cv_ts_ar)
rmsle_xgb_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_xgb_fe_ar_raw, X, y, cv_last30)
rmsle_xgb_fe_ar_last30_log = eval_pipeline_walkforward(pipe_xgb_fe_ar_logtransf, X, y, cv_last30)
rmsle_xgb_fe_ar_ts_raw     = eval_pipeline_walkforward(pipe_xgb_fe_ar_raw, X, y, cv_ts_ar)
rmsle_xgb_fe_ar_ts_log     = eval_pipeline_walkforward(pipe_xgb_fe_ar_logtransf, X, y, cv_ts_ar)
rmsle_cbr_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_cbr_fe_ar_raw, X, y, cv_last30)
rmsle_cbr_fe_ar_last30_log = eval_pipeline_walkforward(pipe_cbr_fe_ar_logtransf, X, y, cv_last30)
rmsle_cbr_fe_ar_ts_raw     = eval_pipeline_walkforward(pipe_cbr_fe_ar_raw, X, y, cv_ts_ar)
rmsle_cbr_fe_ar_ts_log     = eval_pipeline_walkforward(pipe_cbr_fe_ar_logtransf, X, y, cv_ts_ar)
rmsle_lgbm_fe_ar_last30_raw = eval_pipeline_walkforward(pipe_lgbm_fe_ar_raw, X, y, cv_last30)
rmsle_lgbm_fe_ar_last30_log = eval_pipeline_walkforward(pipe_lgbm_fe_ar_logtransf, X, y, cv_last30)
rmsle_lgbm_fe_ar_ts_raw     = eval_pipeline_walkforward(pipe_lgbm_fe_ar_raw, X, y, cv_ts_ar)
rmsle_lgbm_fe_ar_ts_log     = eval_pipeline_walkforward(pipe_lgbm_fe_ar_logtransf, X, y, cv_ts_ar)
print(f"RF + FE (with AR), Last30 split, raw : {rmsle_rf_fe_ar_last30_raw:.6f}")
print(f"RF + FE (with AR), Last30 split, log : {rmsle_rf_fe_ar_last30_log:.6f}")
print(f"HGBRT + FE (with AR), Last30 split, raw : {rmsle_fe_ar_hgbr_last30_raw:.6f}")
print(f"HGBRT + FE (with AR), Last30 log : {rmsle_fe_ar_hgbr_last30_log:.6f}")
print(f"GBRT + FE (with AR), Last30 split, raw : {rmsle_gbr_fe_ar_last30_raw:.6f}")
print(f"GBRT + FE (with AR), Last30 split, log : {rmsle_gbr_fe_ar_last30_log:.6f}")
print(f"XGB + FE (with AR), Last30 split, raw : {rmsle_xgb_fe_ar_last30_raw:.6f}")
print(f"XGB + FE (with AR), Last30 split, log : {rmsle_xgb_fe_ar_last30_log:.6f}")
print(f"CAT + FE (with AR), Last30 split, raw : {rmsle_cbr_fe_ar_last30_raw:.6f}")
print(f"CAT + FE (with AR), Last30 split, log : {rmsle_cbr_fe_ar_last30_log:.6f}")
print(f"LGBM + FE (with AR), Last30 split, raw : {rmsle_lgbm_fe_ar_last30_raw:.6f}")
print(f"LGBM + FE (with AR), Last30 split, log : {rmsle_lgbm_fe_ar_last30_log:.6f}")
print(f"RF + FE (with AR), TS split, raw : {rmsle_rf_fe_ar_ts_raw:.6f}")
print(f"RF + FE (with AR), TS split, log : {rmsle_rf_fe_ar_ts_log:.6f}")
print(f"HGBRT + FE (with AR),  TS   raw : {rmsle_fe_ar_hgbr_ts_raw:.6f}")
print(f"HGBRT + FE (with AR),  TS   log : {rmsle_fe_ar_hgbr_ts_log:.6f}")
print(f"GBRT + FE (with AR), TS split, raw : {rmsle_gbr_fe_ar_ts_raw:.6f}")
print(f"GBRT + FE (with AR), TS split, log : {rmsle_gbr_fe_ar_ts_log:.6f}")
print(f"XGB + FE (with AR), TS split, raw : {rmsle_xgb_fe_ar_ts_raw:.6f}")
print(f"XGB + FE (with AR), TS split, log : {rmsle_xgb_fe_ar_ts_log:.6f}")
print(f"CAT + FE (with AR), TS split, raw : {rmsle_cbr_fe_ar_ts_raw:.6f}")
print(f"CAT + FE (with AR), TS split, log : {rmsle_cbr_fe_ar_ts_log:.6f}")
print(f"LGBM + FE (with AR), TS split, raw : {rmsle_lgbm_fe_ar_ts_raw:.6f}")
print(f"LGBM + FE (with AR), TS split, log : {rmsle_lgbm_fe_ar_ts_log:.6f}")
print()

##########################################
# 3.2.10) Diagnostics: multicollinearity on engineered features (TRAIN ONLY)
##########################################
# Why train-only: avoid peeking at the test distribution and keep diagnostics fold-consistent. Use TSS per sklearn docs. 
# (TimeSeriesSplit is the correct CV for ordered data; 'gap' protects AR features.)  # refs: sklearn TSS docs
# Helper: VIF
def compute_vif(df: pd.DataFrame) -> pd.DataFrame:
    Xn = df.select_dtypes(include=[np.number]).copy()
    # add intercept for OLS-style VIF computation
    Xn.insert(0, "_intercept", 1.0)
    vifs = []
    A = Xn.to_numpy()
    cols = Xn.columns.tolist()
    for j, col in enumerate(cols[1:], start=1):  # skip intercept at 0
        yj = A[:, j]
        Xj = np.delete(A, j, axis=1)
        r2 = LinearRegression(fit_intercept=False).fit(Xj, yj).score(Xj, yj)
        # guard against numerical 1.0
        vif = np.inf if r2 >= 1 - 1e-12 else 1.0 / (1.0 - r2)
        vifs.append((col, float(vif)))
    return pd.DataFrame(vifs, columns=["feature", "VIF"]).sort_values("VIF", ascending=False)

def diagnose_multicollinearity(add_lag1: bool, add_roll7: bool, cv):
    """
    Build engineered TRAIN matrix for one fold, then:
      1) plot correlation heatmap
      2) print top VIFs
    """
    tr_idx, _ = next(cv.split(X))                     # first fold, TRAIN ONLY
    X_tr = X.iloc[tr_idx].copy()

    fe = BikeFeatureEngineer(add_lag1=add_lag1, add_roll7=add_roll7)
    fe_fit = clone(fe).fit(X_tr)                      # fit FE on train
    Z_tr = fe_fit.transform(X_tr)                     # engineered train design matrix

    # 1) Correlation heatmap (pairwise) with annotations and upper-triangle mask
    corr = Z_tr.corr(numeric_only=True)
    mask = np.triu(np.ones_like(corr, dtype=bool), k=1)  # hide upper triangle
    fig, ax = plt.subplots(figsize=(12, 9))
    sns.heatmap(
        corr, mask=mask, cmap="vlag", center=0, vmin=-1, vmax=1,
        square=True, linewidths=.5, linecolor='white',
        annot=True, fmt=".2f", annot_kws={"size":8}, ax=ax
    )
    ax.set_title(f"Post-FE correlations (train-only). AR: lag1={add_lag1}, roll7={add_roll7}")
    plt.tight_layout()
    savefig_pdf(f"fig_corr_train_only_AR_{add_lag1}_{add_roll7}", FIGDIR, fig)


    # 2) VIF (multivariate collinearity)
    vif_df = compute_vif(Z_tr)
    print("Top VIFs (train-only):")
    print(vif_df.head(20).to_string(index=False))
    return vif_df

# Run diagnostics for both settings you evaluate with CV
print("\n=== Multicollinearity diagnostics: NO AR features ===")
vif_no_ar  = diagnose_multicollinearity(add_lag1=False, add_roll7=False, cv=cv_ts_no)

print("\n=== Multicollinearity diagnostics: WITH AR features ===")
vif_with_ar = diagnose_multicollinearity(add_lag1=True,  add_roll7=True,  cv=cv_ts_ar)




"""# Potential improvements
-   Hyperparameter tuning of the RF
-   Add more features:
  - autoregressive: rolling mean instead of median, or as well as rolling median; lag-based feature, not only computed from `cnt` but also from `casual` and `registered`(if not heavily correlated with `cnt`)
  - weather: "pleasant_weather", for example if temp > 0.5 and hum < 0.6. For this, I would read in detail the paper that created the UCI dataset, plus articles on how weather and bike rental forecasts are related, etc.
- Explore feature importance
- Try new models
  - Gradient-boosted trees: they keep learning from the errors of previous trees, thus reducing bias and capturing subtler patterns than an RF, which just averages many independent trees
  - Time-series specific (maybe, if not even GBT works?): something like Prophet? Would need further exploration...
- The dataset is very tiny so the model might not be learning a lot: try retraining after gathering more data

## References

[1] Lichman, M. (2013). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science.
"""
